// Typical starting XIs, 2025-26 season (club) and recent internationals (national teams).
// rows are ordered goalkeeper-first; each row is laid out left-to-right on the pitch.
window.APP_DATA = {
  // country of every club that appears in lineups (shown in bios for context)
  clubCountries: {
    Everton: "England", "Crystal Palace": "England", "Nottingham Forest": "England",
    "Newcastle United": "England", "Aston Villa": "England", Fulham: "England",
    Brentford: "England", Sunderland: "England", Southampton: "England",
    "Leicester City": "England", "Stoke City": "England", "Leeds United": "England",
    "West Bromwich Albion": "England", "Birmingham City": "England", Bournemouth: "England",
    "Preston North End": "England", "Bolton Wanderers": "England", "Exeter City": "England",
    Wolves: "England", "Brighton & Hove Albion": "England", "West Ham United": "England",
    Rangers: "Scotland", Celtic: "Scotland",
    "Real Sociedad": "Spain", "Athletic Club": "Spain", Sevilla: "Spain", Osasuna: "Spain",
    Mallorca: "Spain", Villarreal: "Spain", Espanyol: "Spain", Levante: "Spain",
    Alavés: "Spain", Girona: "Spain", "Real Betis": "Spain",
    Roma: "Italy", Napoli: "Italy", Atalanta: "Italy", Juventus: "Italy", Lazio: "Italy",
    Genoa: "Italy", Bologna: "Italy", Fiorentina: "Italy", Parma: "Italy", Como: "Italy",
    Pisa: "Italy", Udinese: "Italy", Cremonese: "Italy", Torino: "Italy",
    "Eintracht Frankfurt": "Germany", "Borussia Dortmund": "Germany", "RB Leipzig": "Germany",
    Hoffenheim: "Germany", "Union Berlin": "Germany", "Mainz 05": "Germany", Freiburg: "Germany",
    "Werder Bremen": "Germany", Wolfsburg: "Germany", "Bayer Leverkusen": "Germany",
    Stuttgart: "Germany", Augsburg: "Germany", "Borussia Mönchengladbach": "Germany",
    Lyon: "France", "Le Havre": "France", Marseille: "France", Monaco: "France",
    Auxerre: "France", Nice: "France", Strasbourg: "France", Angers: "France",
    Rennes: "France", Nantes: "France", "Saint-Étienne": "France",
    Porto: "Portugal", "Sporting CP": "Portugal", Benfica: "Portugal",
    "AZ Alkmaar": "Netherlands", Ajax: "Netherlands", "PSV Eindhoven": "Netherlands",
    Utrecht: "Netherlands",
    Fenerbahçe: "Turkey", Kasımpaşa: "Turkey", Galatasaray: "Turkey", Trabzonspor: "Turkey",
    Beşiktaş: "Turkey",
    "Al-Hilal": "Saudi Arabia", "Al-Nassr": "Saudi Arabia", "Al-Qadsiah": "Saudi Arabia",
    "Al-Fayha": "Saudi Arabia", "Al-Ahli": "Saudi Arabia", "Neom SC": "Saudi Arabia",
    Flamengo: "Brazil", Corinthians: "Brazil", "São Paulo": "Brazil", Internacional: "Brazil",
    "Inter Miami": "USA", "San Diego FC": "USA", "Charlotte FC": "USA",
    "New York City FC": "USA", "Seattle Sounders": "USA", "Orlando City": "USA",
    "Atlanta United": "USA",
    Atlas: "Mexico", "Club León": "Mexico", "Pumas UNAM": "Mexico", Pachuca: "Mexico",
    Ferencváros: "Hungary", "Lech Poznań": "Poland", "Górnik Zabrze": "Poland",
    "Legia Warsaw": "Poland", Cracovia: "Poland",
    Brøndby: "Denmark", "Red Star Belgrade": "Serbia", Krasnodar: "Russia",
    "Spartak Moscow": "Russia", "Dynamo Moscow": "Russia",
    PAOK: "Greece", "AEK Athens": "Greece", Panathinaikos: "Greece",
    "St. Gallen": "Switzerland", Anderlecht: "Belgium", "Sparta Prague": "Czechia",
    Huracán: "Argentina", Zamalek: "Egypt", "Al Ahly": "Egypt",
    Celje: "Slovenia", "Slovan Bratislava": "Slovakia", APOEL: "Cyprus",
    "Universitatea Craiova": "Romania", "Sturm Graz": "Austria",
  },

  // captains (regular armband wearer where the official captain isn't in the shown XI)
  captains: {
    clubs: {
      Arsenal: "Martin Ødegaard",
      "Manchester City": "Bernardo Silva",
      Liverpool: "Virgil van Dijk",
      Chelsea: "Reece James",
      "Manchester United": "Bruno Fernandes",
      "Tottenham Hotspur": "Cristian Romero",
      "Real Madrid": "Federico Valverde",
      Barcelona: "Ronald Araújo",
      "Bayern Munich": "Manuel Neuer",
      "Paris Saint-Germain": "Marquinhos",
      "Inter Milan": "Lautaro Martínez",
      "AC Milan": "Mike Maignan",
      "Atlético Madrid": "Jan Oblak",
    },
    nations: {
      "gb-eng": "Harry Kane",
      fr: "Kylian Mbappé",
      br: "Marquinhos",
      es: "Unai Simón",
      nl: "Virgil van Dijk",
      pt: "Cristiano Ronaldo",
      ar: "Lionel Messi",
      be: "Kevin De Bruyne",
      it: "Gianluigi Donnarumma",
      no: "Martin Ødegaard",
      se: "Victor Lindelöf",
      hr: "Luka Modrić",
      hu: "Dominik Szoboszlai",
      "gb-nir": "Conor Bradley",
      de: "Joshua Kimmich",
      eg: "Mohamed Salah",
      ec: "Enner Valencia",
      ci: "Franck Kessié",
      dk: "Pierre-Emile Højbjerg",
      cm: "André-Frank Zambo Anguissa",
      si: "Jan Oblak",
      uy: "Federico Valverde",
      gh: "Jordan Ayew",
      pl: "Robert Lewandowski",
      at: "Marcel Sabitzer",
      co: "James Rodríguez",
      rs: "Sergej Milinković-Savić",
      us: "Tyler Adams",
      ch: "Granit Xhaka",
      tr: "Hakan Çalhanoğlu",
      ma: "Achraf Hakimi",
      ge: "Khvicha Kvaratskhelia",
    },
  },

  // ambient colors per national team (primary, secondary) for the pitch backdrop
  nationColors: {
    "gb-eng": ["#CE1124", "#FFFFFF"],
    fr: ["#0055A4", "#EF4135"],
    br: ["#009C3B", "#FFDF00"],
    es: ["#AA151B", "#F1BF00"],
    nl: ["#F36C21", "#21468B"],
    pt: ["#DA291C", "#046A38"],
    ar: ["#75AADB", "#F6B40E"],
    be: ["#ED2939", "#FDDA24"],
    it: ["#008C45", "#CD212A"],
    no: ["#BA0C2F", "#00205B"],
    se: ["#006AA7", "#FECC02"],
    hr: ["#E73446", "#171796"],
    hu: ["#CE2939", "#477050"],
    "gb-nir": ["#CE1124", "#FFFFFF"],
    de: ["#DD0000", "#FFCE00"],
    eg: ["#CE1126", "#C09300"],
    ec: ["#FFDD00", "#034EA2"],
    ci: ["#F77F00", "#009E60"],
    dk: ["#C8102E", "#FFFFFF"],
    cm: ["#007A5E", "#CE1126"],
    si: ["#1E5AA8", "#ED1C24"],
    uy: ["#5CBFEB", "#FFD100"],
    gh: ["#CE1126", "#FCD116"],
    pl: ["#DC143C", "#FFFFFF"],
    at: ["#ED2939", "#FFFFFF"],
    co: ["#FCD116", "#003893"],
    rs: ["#C6363C", "#0C4076"],
    us: ["#3C3B6E", "#B22234"],
    ch: ["#D52B1E", "#FFFFFF"],
    tr: ["#E30A17", "#FFFFFF"],
    ma: ["#C1272D", "#006233"],
    ge: ["#DA291C", "#FFFFFF"],
  },

  // shown in the right-edge rail, ordered by World Cup seeding (FIFA ranking at the Dec 2025 draw)
  featuredNations: ["es", "ar", "fr", "gb-eng", "br", "pt", "nl", "be", "de", "hr", "ma", "it", "co", "us", "uy", "no"],

  // the marquee names of the 2026 World Cup: club + country at a glance
  topPlayers: [
    { name: "Lionel Messi", pos: "RW", club: "Inter Miami", nation: "ar", note: "8× Ballon d'Or · defending champion, chasing a final bow" },
    { name: "Kylian Mbappé", pos: "ST", club: "Real Madrid", nation: "fr", note: "France captain · 2022 final hat-trick hero" },
    { name: "Ousmane Dembélé", pos: "LW", club: "Paris Saint-Germain", nation: "fr", note: "2025 Ballon d'Or winner" },
    { name: "Erling Haaland", pos: "ST", club: "Manchester City", nation: "no", note: "Goal machine · Norway's first World Cup since 1998" },
    { name: "Vinícius Júnior", pos: "LW", club: "Real Madrid", nation: "br", note: "Brazil's talisman" },
    { name: "Lamine Yamal", pos: "RW", club: "Barcelona", nation: "es", note: "Teenage phenom · Euro 2024 champion" },
    { name: "Jude Bellingham", pos: "AM", club: "Real Madrid", nation: "gb-eng", note: "England's midfield engine" },
    { name: "Harry Kane", pos: "ST", club: "Bayern Munich", nation: "gb-eng", note: "England captain and record scorer" },
    { name: "Mohamed Salah", pos: "RW", club: "Liverpool", nation: "eg", note: "Egyptian king · Africa's biggest star" },
    { name: "Cristiano Ronaldo", pos: "ST", club: "Al-Nassr", nation: "pt", note: "5× Ballon d'Or · one last World Cup at 41" },
    { name: "Florian Wirtz", pos: "AM", club: "Liverpool", nation: "de", note: "Germany's creative heartbeat" },
    { name: "Kevin De Bruyne", pos: "AM", club: "Napoli", nation: "be", note: "Belgium's golden-generation closer" },
    { name: "Luka Modrić", pos: "CM", club: "AC Milan", nation: "hr", note: "2018 Ballon d'Or · still running Croatia at 40" },
    { name: "Rodri", pos: "DM", club: "Manchester City", nation: "es", note: "2024 Ballon d'Or · Spain's anchor" },
    { name: "Julián Álvarez", pos: "ST", club: "Atlético Madrid", nation: "ar", note: "World champion · Atlético's spearhead" },
    { name: "Lautaro Martínez", pos: "ST", club: "Inter Milan", nation: "ar", note: "Inter captain" },
    { name: "Bukayo Saka", pos: "RW", club: "Arsenal", nation: "gb-eng", note: "Arsenal's star boy" },
    { name: "Khvicha Kvaratskhelia", pos: "LW", club: "Paris Saint-Germain", nation: "ge", note: "Kvaradona · Georgia's first World Cup" },
    { name: "Christian Pulisic", pos: "LW", club: "AC Milan", nation: "us", note: "Captain America · host-nation hope" },
    { name: "Virgil van Dijk", pos: "CB", club: "Liverpool", nation: "nl", note: "The Netherlands' colossus" },
    { name: "Federico Valverde", pos: "CM", club: "Real Madrid", nation: "uy", note: "Uruguay's all-action leader" },
    { name: "Robert Lewandowski", pos: "ST", club: "Barcelona", nation: "pl", note: "Poland's record scorer" },
    { name: "Achraf Hakimi", pos: "RB", club: "Paris Saint-Germain", nation: "ma", note: "Morocco's 2022 semifinal hero" },
    { name: "Alexander Isak", pos: "ST", club: "Liverpool", nation: "se", note: "British-record signing" },
  ],
  clubs: [
    {
      id: "arsenal",
      name: "Arsenal",
      short: "Arsenal",
      badge: "https://resources.premierleague.com/premierleague/badges/100/t3@x2.png",
      color: "#EF0107",
      formation: "4-3-3",
      rows: [
        [{ name: "David Raya", pos: "GK", nation: "es" }],
        [
          { name: "Riccardo Calafiori", pos: "LB", nation: "it" },
          { name: "Gabriel Magalhães", pos: "CB", nation: "br" },
          { name: "William Saliba", pos: "CB", nation: "fr" },
          { name: "Jurriën Timber", pos: "RB", nation: "nl" },
        ],
        [
          { name: "Declan Rice", pos: "CM", nation: "gb-eng" },
          { name: "Martín Zubimendi", pos: "DM", nation: "es" },
          { name: "Martin Ødegaard", pos: "CM", nation: "no" },
        ],
        [
          { name: "Eberechi Eze", pos: "LW", nation: "gb-eng" },
          { name: "Viktor Gyökeres", pos: "ST", nation: "se" },
          { name: "Bukayo Saka", pos: "RW", nation: "gb-eng" },
        ],
      ],
    },
    {
      id: "man-city",
      name: "Manchester City",
      short: "Man City",
      badge: "https://resources.premierleague.com/premierleague/badges/100/t43@x2.png",
      color: "#6CABDD",
      formation: "4-3-3",
      rows: [
        [{ name: "Gianluigi Donnarumma", pos: "GK", nation: "it" }],
        [
          { name: "Nico O'Reilly", pos: "LB", nation: "gb-eng" },
          { name: "Josko Gvardiol", pos: "CB", nation: "hr" },
          { name: "Rúben Dias", pos: "CB", nation: "pt" },
          { name: "Matheus Nunes", pos: "RB", nation: "pt" },
        ],
        [
          { name: "Tijjani Reijnders", pos: "CM", nation: "nl" },
          { name: "Rodri", pos: "DM", nation: "es" },
          { name: "Bernardo Silva", pos: "CM", nation: "pt" },
        ],
        [
          { name: "Jérémy Doku", pos: "LW", nation: "be" },
          { name: "Erling Haaland", pos: "ST", nation: "no" },
          { name: "Phil Foden", pos: "RW", nation: "gb-eng" },
        ],
      ],
    },
    {
      id: "liverpool",
      name: "Liverpool",
      short: "Liverpool",
      badge: "https://resources.premierleague.com/premierleague/badges/100/t14@x2.png",
      color: "#C8102E",
      formation: "4-2-3-1",
      rows: [
        [{ name: "Alisson Becker", pos: "GK", nation: "br" }],
        [
          { name: "Milos Kerkez", pos: "LB", nation: "hu" },
          { name: "Virgil van Dijk", pos: "CB", nation: "nl" },
          { name: "Ibrahima Konaté", pos: "CB", nation: "fr" },
          { name: "Conor Bradley", pos: "RB", nation: "gb-nir" },
        ],
        [
          { name: "Ryan Gravenberch", pos: "DM", nation: "nl" },
          { name: "Alexis Mac Allister", pos: "CM", nation: "ar" },
        ],
        [
          { name: "Florian Wirtz", pos: "LW", nation: "de" },
          { name: "Dominik Szoboszlai", pos: "AM", nation: "hu" },
          { name: "Mohamed Salah", pos: "RW", nation: "eg" },
        ],
        [{ name: "Alexander Isak", pos: "ST", nation: "se" }],
      ],
    },
    {
      id: "chelsea",
      name: "Chelsea",
      short: "Chelsea",
      badge: "https://resources.premierleague.com/premierleague/badges/100/t8@x2.png",
      color: "#034694",
      formation: "4-2-3-1",
      rows: [
        [{ name: "Robert Sánchez", pos: "GK", nation: "es" }],
        [
          { name: "Marc Cucurella", pos: "LB", nation: "es" },
          { name: "Trevoh Chalobah", pos: "CB", nation: "gb-eng" },
          { name: "Wesley Fofana", pos: "CB", nation: "fr" },
          { name: "Reece James", pos: "RB", nation: "gb-eng" },
        ],
        [
          { name: "Moisés Caicedo", pos: "DM", nation: "ec" },
          { name: "Enzo Fernández", pos: "CM", nation: "ar" },
        ],
        [
          { name: "Alejandro Garnacho", pos: "LW", nation: "ar" },
          { name: "Cole Palmer", pos: "AM", nation: "gb-eng" },
          { name: "Pedro Neto", pos: "RW", nation: "pt" },
        ],
        [{ name: "João Pedro", pos: "ST", nation: "br" }],
      ],
    },
    {
      id: "man-united",
      name: "Manchester United",
      short: "Man United",
      badge: "https://resources.premierleague.com/premierleague/badges/100/t1@x2.png",
      color: "#DA291C",
      formation: "3-4-2-1",
      rows: [
        [{ name: "Senne Lammens", pos: "GK", nation: "be" }],
        [
          { name: "Luke Shaw", pos: "CB", nation: "gb-eng" },
          { name: "Matthijs de Ligt", pos: "CB", nation: "nl" },
          { name: "Leny Yoro", pos: "CB", nation: "fr" },
        ],
        [
          { name: "Patrick Dorgu", pos: "LWB", nation: "dk" },
          { name: "Casemiro", pos: "CM", nation: "br" },
          { name: "Bruno Fernandes", pos: "CM", nation: "pt" },
          { name: "Amad Diallo", pos: "RWB", nation: "ci" },
        ],
        [
          { name: "Matheus Cunha", pos: "AM", nation: "br" },
          { name: "Bryan Mbeumo", pos: "AM", nation: "cm" },
        ],
        [{ name: "Benjamin Šeško", pos: "ST", nation: "si" }],
      ],
    },
    {
      id: "tottenham",
      name: "Tottenham Hotspur",
      short: "Spurs",
      badge: "https://resources.premierleague.com/premierleague/badges/100/t6@x2.png",
      color: "#132257",
      formation: "4-2-3-1",
      rows: [
        [{ name: "Guglielmo Vicario", pos: "GK", nation: "it" }],
        [
          { name: "Destiny Udogie", pos: "LB", nation: "it" },
          { name: "Micky van de Ven", pos: "CB", nation: "nl" },
          { name: "Cristian Romero", pos: "CB", nation: "ar" },
          { name: "Pedro Porro", pos: "RB", nation: "es" },
        ],
        [
          { name: "João Palhinha", pos: "DM", nation: "pt" },
          { name: "Rodrigo Bentancur", pos: "CM", nation: "uy" },
        ],
        [
          { name: "Wilson Odobert", pos: "LW", nation: "fr" },
          { name: "Xavi Simons", pos: "AM", nation: "nl" },
          { name: "Mohammed Kudus", pos: "RW", nation: "gh" },
        ],
        [{ name: "Richarlison", pos: "ST", nation: "br" }],
      ],
    },
    {
      id: "real-madrid",
      name: "Real Madrid",
      short: "Real Madrid",
      badge: "https://upload.wikimedia.org/wikipedia/en/thumb/5/56/Real_Madrid_CF.svg/330px-Real_Madrid_CF.svg.png",
      color: "#FEBE10",
      formation: "4-3-3",
      rows: [
        [{ name: "Thibaut Courtois", pos: "GK", nation: "be" }],
        [
          { name: "Álvaro Carreras", pos: "LB", nation: "es" },
          { name: "Dean Huijsen", pos: "CB", nation: "es" },
          { name: "Éder Militão", pos: "CB", nation: "br" },
          { name: "Trent Alexander-Arnold", pos: "RB", nation: "gb-eng" },
        ],
        [
          { name: "Aurélien Tchouaméni", pos: "DM", nation: "fr" },
          { name: "Federico Valverde", pos: "CM", nation: "uy" },
          { name: "Jude Bellingham", pos: "AM", nation: "gb-eng" },
        ],
        [
          { name: "Vinícius Júnior", pos: "LW", nation: "br" },
          { name: "Kylian Mbappé", pos: "ST", nation: "fr" },
          { name: "Franco Mastantuono", pos: "RW", nation: "ar" },
        ],
      ],
    },
    {
      id: "barcelona",
      name: "Barcelona",
      short: "Barcelona",
      badge: "https://upload.wikimedia.org/wikipedia/en/thumb/4/47/FC_Barcelona_%28crest%29.svg/330px-FC_Barcelona_%28crest%29.svg.png",
      color: "#A50044",
      formation: "4-2-3-1",
      rows: [
        [{ name: "Joan García", pos: "GK", nation: "es" }],
        [
          { name: "Alejandro Balde", pos: "LB", nation: "es" },
          { name: "Pau Cubarsí", pos: "CB", nation: "es" },
          { name: "Ronald Araújo", pos: "CB", nation: "uy" },
          { name: "Jules Koundé", pos: "RB", nation: "fr" },
        ],
        [
          { name: "Pedri", pos: "CM", nation: "es" },
          { name: "Frenkie de Jong", pos: "CM", nation: "nl" },
        ],
        [
          { name: "Raphinha", pos: "LW", nation: "br" },
          { name: "Dani Olmo", pos: "AM", nation: "es" },
          { name: "Lamine Yamal", pos: "RW", nation: "es" },
        ],
        [{ name: "Robert Lewandowski", pos: "ST", nation: "pl" }],
      ],
    },
    {
      id: "bayern",
      name: "Bayern Munich",
      short: "Bayern",
      badge: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/FC_Bayern_M%C3%BCnchen_logo_%282024%29.svg/330px-FC_Bayern_M%C3%BCnchen_logo_%282024%29.svg.png",
      color: "#DC052D",
      formation: "4-2-3-1",
      rows: [
        [{ name: "Manuel Neuer", pos: "GK", nation: "de" }],
        [
          { name: "Josip Stanišić", pos: "LB", nation: "hr" },
          { name: "Dayot Upamecano", pos: "CB", nation: "fr" },
          { name: "Jonathan Tah", pos: "CB", nation: "de" },
          { name: "Konrad Laimer", pos: "RB", nation: "at" },
        ],
        [
          { name: "Joshua Kimmich", pos: "DM", nation: "de" },
          { name: "Aleksandar Pavlović", pos: "CM", nation: "de" },
        ],
        [
          { name: "Luis Díaz", pos: "LW", nation: "co" },
          { name: "Serge Gnabry", pos: "AM", nation: "de" },
          { name: "Michael Olise", pos: "RW", nation: "fr" },
        ],
        [{ name: "Harry Kane", pos: "ST", nation: "gb-eng" }],
      ],
    },
    {
      id: "psg",
      name: "Paris Saint-Germain",
      short: "PSG",
      badge: "https://upload.wikimedia.org/wikipedia/en/thumb/a/a7/Paris_Saint-Germain_F.C..svg/330px-Paris_Saint-Germain_F.C..svg.png",
      color: "#004170",
      formation: "4-3-3",
      rows: [
        [{ name: "Lucas Chevalier", pos: "GK", nation: "fr" }],
        [
          { name: "Nuno Mendes", pos: "LB", nation: "pt" },
          { name: "Willian Pacho", pos: "CB", nation: "ec" },
          { name: "Marquinhos", pos: "CB", nation: "br" },
          { name: "Achraf Hakimi", pos: "RB", nation: "ma" },
        ],
        [
          { name: "João Neves", pos: "CM", nation: "pt" },
          { name: "Vitinha", pos: "DM", nation: "pt" },
          { name: "Fabián Ruiz", pos: "CM", nation: "es" },
        ],
        [
          { name: "Khvicha Kvaratskhelia", pos: "LW", nation: "ge" },
          { name: "Ousmane Dembélé", pos: "ST", nation: "fr" },
          { name: "Désiré Doué", pos: "RW", nation: "fr" },
        ],
      ],
    },
    {
      id: "inter",
      name: "Inter Milan",
      short: "Inter",
      badge: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/FC_Internazionale_Milano_2021.svg/330px-FC_Internazionale_Milano_2021.svg.png",
      color: "#010E80",
      formation: "3-5-2",
      rows: [
        [{ name: "Yann Sommer", pos: "GK", nation: "ch" }],
        [
          { name: "Alessandro Bastoni", pos: "CB", nation: "it" },
          { name: "Francesco Acerbi", pos: "CB", nation: "it" },
          { name: "Manuel Akanji", pos: "CB", nation: "ch" },
        ],
        [
          { name: "Federico Dimarco", pos: "LWB", nation: "it" },
          { name: "Petar Sučić", pos: "CM", nation: "hr" },
          { name: "Hakan Çalhanoğlu", pos: "DM", nation: "tr" },
          { name: "Nicolò Barella", pos: "CM", nation: "it" },
          { name: "Denzel Dumfries", pos: "RWB", nation: "nl" },
        ],
        [
          { name: "Lautaro Martínez", pos: "ST", nation: "ar" },
          { name: "Marcus Thuram", pos: "ST", nation: "fr" },
        ],
      ],
    },
    {
      id: "ac-milan",
      name: "AC Milan",
      short: "AC Milan",
      markScale: 0.72,
      badge: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Logo_of_AC_Milan.svg/330px-Logo_of_AC_Milan.svg.png",
      color: "#FB090B",
      formation: "3-5-2",
      rows: [
        [{ name: "Mike Maignan", pos: "GK", nation: "fr" }],
        [
          { name: "Strahinja Pavlović", pos: "CB", nation: "rs" },
          { name: "Matteo Gabbia", pos: "CB", nation: "it" },
          { name: "Fikayo Tomori", pos: "CB", nation: "gb-eng" },
        ],
        [
          { name: "Pervis Estupiñán", pos: "LWB", nation: "ec" },
          { name: "Adrien Rabiot", pos: "CM", nation: "fr" },
          { name: "Luka Modrić", pos: "DM", nation: "hr" },
          { name: "Youssouf Fofana", pos: "CM", nation: "fr" },
          { name: "Alexis Saelemaekers", pos: "RWB", nation: "be" },
        ],
        [
          { name: "Christian Pulisic", pos: "ST", nation: "us" },
          { name: "Rafael Leão", pos: "ST", nation: "pt" },
        ],
      ],
    },
    {
      id: "atletico",
      name: "Atlético Madrid",
      short: "Atlético",
      badge: "https://upload.wikimedia.org/wikipedia/en/thumb/f/f9/Atletico_Madrid_Logo_2024.svg/330px-Atletico_Madrid_Logo_2024.svg.png",
      color: "#CB3524",
      formation: "4-4-2",
      rows: [
        [{ name: "Jan Oblak", pos: "GK", nation: "si" }],
        [
          { name: "Matteo Ruggeri", pos: "LB", nation: "it" },
          { name: "José María Giménez", pos: "CB", nation: "uy" },
          { name: "Robin Le Normand", pos: "CB", nation: "es" },
          { name: "Nahuel Molina", pos: "RB", nation: "ar" },
        ],
        [
          { name: "Álex Baena", pos: "LM", nation: "es" },
          { name: "Pablo Barrios", pos: "CM", nation: "es" },
          { name: "Conor Gallagher", pos: "CM", nation: "gb-eng" },
          { name: "Giuliano Simeone", pos: "RM", nation: "ar" },
        ],
        [
          { name: "Julián Álvarez", pos: "ST", nation: "ar" },
          { name: "Antoine Griezmann", pos: "ST", nation: "fr" },
        ],
      ],
    },
  ],

  nations: {
    "gb-eng": {
      name: "England",
      formation: "4-2-3-1",
      rows: [
        [{ name: "Jordan Pickford", pos: "GK", club: "Everton" }],
        [
          { name: "Myles Lewis-Skelly", pos: "LB", club: "Arsenal" },
          { name: "Marc Guéhi", pos: "CB", club: "Crystal Palace" },
          { name: "John Stones", pos: "CB", club: "Manchester City" },
          { name: "Reece James", pos: "RB", club: "Chelsea" },
        ],
        [
          { name: "Declan Rice", pos: "DM", club: "Arsenal" },
          { name: "Elliot Anderson", pos: "CM", club: "Nottingham Forest" },
        ],
        [
          { name: "Anthony Gordon", pos: "LW", club: "Newcastle United" },
          { name: "Jude Bellingham", pos: "AM", club: "Real Madrid" },
          { name: "Bukayo Saka", pos: "RW", club: "Arsenal" },
        ],
        [{ name: "Harry Kane", pos: "ST", club: "Bayern Munich" }],
      ],
    },
    fr: {
      name: "France",
      formation: "4-3-3",
      rows: [
        [{ name: "Mike Maignan", pos: "GK", club: "AC Milan" }],
        [
          { name: "Théo Hernandez", pos: "LB", club: "Al-Hilal" },
          { name: "Ibrahima Konaté", pos: "CB", club: "Liverpool" },
          { name: "William Saliba", pos: "CB", club: "Arsenal" },
          { name: "Jules Koundé", pos: "RB", club: "Barcelona" },
        ],
        [
          { name: "Manu Koné", pos: "CM", club: "Roma" },
          { name: "Aurélien Tchouaméni", pos: "DM", club: "Real Madrid" },
          { name: "Adrien Rabiot", pos: "CM", club: "AC Milan" },
        ],
        [
          { name: "Ousmane Dembélé", pos: "LW", club: "Paris Saint-Germain" },
          { name: "Kylian Mbappé", pos: "ST", club: "Real Madrid" },
          { name: "Michael Olise", pos: "RW", club: "Bayern Munich" },
        ],
      ],
    },
    br: {
      name: "Brazil",
      formation: "4-2-3-1",
      rows: [
        [{ name: "Alisson Becker", pos: "GK", club: "Liverpool" }],
        [
          { name: "Alex Sandro", pos: "LB", club: "Flamengo" },
          { name: "Gabriel Magalhães", pos: "CB", club: "Arsenal" },
          { name: "Marquinhos", pos: "CB", club: "Paris Saint-Germain" },
          { name: "Wesley França", pos: "RB", club: "Roma" },
        ],
        [
          { name: "Casemiro", pos: "DM", club: "Manchester United" },
          { name: "Bruno Guimarães", pos: "CM", club: "Newcastle United" },
        ],
        [
          { name: "Vinícius Júnior", pos: "LW", club: "Real Madrid" },
          { name: "Matheus Cunha", pos: "AM", club: "Manchester United" },
          { name: "Estêvão", pos: "RW", club: "Chelsea" },
        ],
        [{ name: "João Pedro", pos: "ST", club: "Chelsea" }],
      ],
    },
    es: {
      name: "Spain",
      formation: "4-3-3",
      rows: [
        [{ name: "Unai Simón", pos: "GK", club: "Athletic Club" }],
        [
          { name: "Marc Cucurella", pos: "LB", club: "Chelsea" },
          { name: "Dean Huijsen", pos: "CB", club: "Real Madrid" },
          { name: "Robin Le Normand", pos: "CB", club: "Atlético Madrid" },
          { name: "Pedro Porro", pos: "RB", club: "Tottenham Hotspur" },
        ],
        [
          { name: "Pedri", pos: "CM", club: "Barcelona" },
          { name: "Martín Zubimendi", pos: "DM", club: "Arsenal" },
          { name: "Mikel Merino", pos: "CM", club: "Arsenal" },
        ],
        [
          { name: "Nico Williams", pos: "LW", club: "Athletic Club" },
          { name: "Mikel Oyarzabal", pos: "ST", club: "Real Sociedad" },
          { name: "Lamine Yamal", pos: "RW", club: "Barcelona" },
        ],
      ],
    },
    nl: {
      name: "Netherlands",
      formation: "4-3-3",
      rows: [
        [{ name: "Bart Verbruggen", pos: "GK", club: "Brighton & Hove Albion" }],
        [
          { name: "Micky van de Ven", pos: "LB", club: "Tottenham Hotspur" },
          { name: "Virgil van Dijk", pos: "CB", club: "Liverpool" },
          { name: "Matthijs de Ligt", pos: "CB", club: "Manchester United" },
          { name: "Denzel Dumfries", pos: "RB", club: "Inter Milan" },
        ],
        [
          { name: "Tijjani Reijnders", pos: "CM", club: "Manchester City" },
          { name: "Ryan Gravenberch", pos: "DM", club: "Liverpool" },
          { name: "Frenkie de Jong", pos: "CM", club: "Barcelona" },
        ],
        [
          { name: "Cody Gakpo", pos: "LW", club: "Liverpool" },
          { name: "Brian Brobbey", pos: "ST", club: "Sunderland" },
          { name: "Crysencio Summerville", pos: "RW", club: "West Ham United" },
        ],
      ],
    },
    pt: {
      name: "Portugal",
      formation: "4-3-3",
      rows: [
        [{ name: "Diogo Costa", pos: "GK", club: "Porto" }],
        [
          { name: "Nuno Mendes", pos: "LB", club: "Paris Saint-Germain" },
          { name: "Gonçalo Inácio", pos: "CB", club: "Sporting CP" },
          { name: "Rúben Dias", pos: "CB", club: "Manchester City" },
          { name: "João Cancelo", pos: "RB", club: "Al-Hilal" },
        ],
        [
          { name: "Vitinha", pos: "CM", club: "Paris Saint-Germain" },
          { name: "João Neves", pos: "CM", club: "Paris Saint-Germain" },
          { name: "Bruno Fernandes", pos: "CM", club: "Manchester United" },
        ],
        [
          { name: "Pedro Neto", pos: "LW", club: "Chelsea" },
          { name: "Cristiano Ronaldo", pos: "ST", club: "Al-Nassr" },
          { name: "Bernardo Silva", pos: "RW", club: "Manchester City" },
        ],
      ],
    },
    ar: {
      name: "Argentina",
      formation: "4-3-3",
      rows: [
        [{ name: "Emiliano Martínez", pos: "GK", club: "Aston Villa" }],
        [
          { name: "Nicolás Tagliafico", pos: "LB", club: "Lyon" },
          { name: "Cristian Romero", pos: "CB", club: "Tottenham Hotspur" },
          { name: "Nicolás Otamendi", pos: "CB", club: "Benfica" },
          { name: "Nahuel Molina", pos: "RB", club: "Atlético Madrid" },
        ],
        [
          { name: "Alexis Mac Allister", pos: "CM", club: "Liverpool" },
          { name: "Rodrigo De Paul", pos: "CM", club: "Inter Miami" },
          { name: "Enzo Fernández", pos: "CM", club: "Chelsea" },
        ],
        [
          { name: "Thiago Almada", pos: "LW", club: "Atlético Madrid" },
          { name: "Julián Álvarez", pos: "ST", club: "Atlético Madrid" },
          { name: "Lionel Messi", pos: "RW", club: "Inter Miami" },
        ],
      ],
    },
    be: {
      name: "Belgium",
      formation: "4-2-3-1",
      rows: [
        [{ name: "Thibaut Courtois", pos: "GK", club: "Real Madrid" }],
        [
          { name: "Arthur Theate", pos: "LB", club: "Eintracht Frankfurt" },
          { name: "Wout Faes", pos: "CB", club: "Leicester City" },
          { name: "Zeno Debast", pos: "CB", club: "Sporting CP" },
          { name: "Timothy Castagne", pos: "RB", club: "Fulham" },
        ],
        [
          { name: "Amadou Onana", pos: "DM", club: "Aston Villa" },
          { name: "Youri Tielemans", pos: "CM", club: "Aston Villa" },
        ],
        [
          { name: "Jérémy Doku", pos: "LW", club: "Manchester City" },
          { name: "Kevin De Bruyne", pos: "AM", club: "Napoli" },
          { name: "Leandro Trossard", pos: "RW", club: "Arsenal" },
        ],
        [{ name: "Romelu Lukaku", pos: "ST", club: "Napoli" }],
      ],
    },
    it: {
      name: "Italy",
      formation: "4-3-3",
      rows: [
        [{ name: "Gianluigi Donnarumma", pos: "GK", club: "Manchester City" }],
        [
          { name: "Federico Dimarco", pos: "LB", club: "Inter Milan" },
          { name: "Riccardo Calafiori", pos: "CB", club: "Arsenal" },
          { name: "Alessandro Bastoni", pos: "CB", club: "Inter Milan" },
          { name: "Giovanni Di Lorenzo", pos: "RB", club: "Napoli" },
        ],
        [
          { name: "Sandro Tonali", pos: "DM", club: "Newcastle United" },
          { name: "Nicolò Barella", pos: "CM", club: "Inter Milan" },
          { name: "Davide Frattesi", pos: "CM", club: "Inter Milan" },
        ],
        [
          { name: "Mattia Zaccagni", pos: "LW", club: "Lazio" },
          { name: "Mateo Retegui", pos: "ST", club: "Al-Qadsiah" },
          { name: "Matteo Politano", pos: "RW", club: "Napoli" },
        ],
      ],
    },
    no: {
      name: "Norway",
      formation: "4-3-3",
      rows: [
        [{ name: "Ørjan Nyland", pos: "GK", club: "Sevilla" }],
        [
          { name: "David Møller Wolfe", pos: "LB", club: "AZ Alkmaar" },
          { name: "Kristoffer Ajer", pos: "CB", club: "Brentford" },
          { name: "Leo Østigård", pos: "CB", club: "Genoa" },
          { name: "Julian Ryerson", pos: "RB", club: "Borussia Dortmund" },
        ],
        [
          { name: "Sander Berge", pos: "CM", club: "Fulham" },
          { name: "Martin Ødegaard", pos: "CM", club: "Arsenal" },
          { name: "Thelo Aasgaard", pos: "CM", club: "Rangers" },
        ],
        [
          { name: "Antonio Nusa", pos: "LW", club: "RB Leipzig" },
          { name: "Erling Haaland", pos: "ST", club: "Manchester City" },
          { name: "Oscar Bobb", pos: "RW", club: "Manchester City" },
        ],
      ],
    },
    se: {
      name: "Sweden",
      formation: "4-4-2",
      rows: [
        [{ name: "Viktor Johansson", pos: "GK", club: "Stoke City" }],
        [
          { name: "Gabriel Gudmundsson", pos: "LB", club: "Leeds United" },
          { name: "Isak Hien", pos: "CB", club: "Atalanta" },
          { name: "Victor Lindelöf", pos: "CB", club: "Aston Villa" },
          { name: "Emil Holm", pos: "RB", club: "Bologna" },
        ],
        [
          { name: "Lucas Bergvall", pos: "LM", club: "Tottenham Hotspur" },
          { name: "Yasin Ayari", pos: "CM", club: "Brighton & Hove Albion" },
          { name: "Jesper Karlström", pos: "CM", club: "Lech Poznań" },
          { name: "Anthony Elanga", pos: "RM", club: "Newcastle United" },
        ],
        [
          { name: "Viktor Gyökeres", pos: "ST", club: "Arsenal" },
          { name: "Alexander Isak", pos: "ST", club: "Liverpool" },
        ],
      ],
    },
    hr: {
      name: "Croatia",
      formation: "4-3-3",
      rows: [
        [{ name: "Dominik Livaković", pos: "GK", club: "Fenerbahçe" }],
        [
          { name: "Josko Gvardiol", pos: "LB", club: "Manchester City" },
          { name: "Marin Pongračić", pos: "CB", club: "Fiorentina" },
          { name: "Josip Šutalo", pos: "CB", club: "Ajax" },
          { name: "Josip Stanišić", pos: "RB", club: "Bayern Munich" },
        ],
        [
          { name: "Mateo Kovačić", pos: "CM", club: "Manchester City" },
          { name: "Luka Modrić", pos: "CM", club: "AC Milan" },
          { name: "Petar Sučić", pos: "CM", club: "Inter Milan" },
        ],
        [
          { name: "Ivan Perišić", pos: "LW", club: "PSV Eindhoven" },
          { name: "Ante Budimir", pos: "ST", club: "Osasuna" },
          { name: "Andrej Kramarić", pos: "RW", club: "Hoffenheim" },
        ],
      ],
    },
    hu: {
      name: "Hungary",
      formation: "3-4-2-1",
      rows: [
        [{ name: "Dénes Dibusz", pos: "GK", club: "Ferencváros" }],
        [
          { name: "Botond Balogh", pos: "CB", club: "Parma" },
          { name: "Willi Orbán", pos: "CB", club: "RB Leipzig" },
          { name: "Attila Szalai", pos: "CB", club: "Kasımpaşa" },
        ],
        [
          { name: "Milos Kerkez", pos: "LWB", club: "Liverpool" },
          { name: "András Schäfer", pos: "CM", club: "Union Berlin" },
          { name: "Callum Styles", pos: "CM", club: "West Bromwich Albion" },
          { name: "Loïc Négo", pos: "RWB", club: "Le Havre" },
        ],
        [
          { name: "Dominik Szoboszlai", pos: "AM", club: "Liverpool" },
          { name: "Roland Sallai", pos: "AM", club: "Galatasaray" },
        ],
        [{ name: "Barnabás Varga", pos: "ST", club: "Ferencváros" }],
      ],
    },
    "gb-nir": {
      name: "Northern Ireland",
      formation: "3-5-2",
      rows: [
        [{ name: "Bailey Peacock-Farrell", pos: "GK", club: "Birmingham City" }],
        [
          { name: "Trai Hume", pos: "CB", club: "Sunderland" },
          { name: "Daniel Ballard", pos: "CB", club: "Sunderland" },
          { name: "Paddy McNair", pos: "CB", club: "San Diego FC" },
        ],
        [
          { name: "Jamal Lewis", pos: "LWB", club: "São Paulo" },
          { name: "Isaac Price", pos: "CM", club: "West Bromwich Albion" },
          { name: "Shea Charles", pos: "CM", club: "Southampton" },
          { name: "Ali McCann", pos: "CM", club: "Preston North End" },
          { name: "Conor Bradley", pos: "RWB", club: "Liverpool" },
        ],
        [
          { name: "Dion Charles", pos: "ST", club: "Bolton Wanderers" },
          { name: "Josh Magennis", pos: "ST", club: "Exeter City" },
        ],
      ],
    },
    de: {
      name: "Germany",
      formation: "4-2-3-1",
      rows: [
        [{ name: "Oliver Baumann", pos: "GK", club: "Hoffenheim" }],
        [
          { name: "David Raum", pos: "LB", club: "RB Leipzig" },
          { name: "Nico Schlotterbeck", pos: "CB", club: "Borussia Dortmund" },
          { name: "Jonathan Tah", pos: "CB", club: "Bayern Munich" },
          { name: "Joshua Kimmich", pos: "RB", club: "Bayern Munich" },
        ],
        [
          { name: "Aleksandar Pavlović", pos: "CM", club: "Bayern Munich" },
          { name: "Leon Goretzka", pos: "CM", club: "Bayern Munich" },
        ],
        [
          { name: "Leroy Sané", pos: "LW", club: "Galatasaray" },
          { name: "Florian Wirtz", pos: "AM", club: "Liverpool" },
          { name: "Serge Gnabry", pos: "RW", club: "Bayern Munich" },
        ],
        [{ name: "Deniz Undav", pos: "ST", club: "Stuttgart" }],
      ],
    },
    eg: {
      name: "Egypt",
      formation: "4-2-3-1",
      rows: [
        [{ name: "Mohamed El Shenawy", pos: "GK", club: "Al Ahly" }],
        [
          { name: "Ahmed Fatouh", pos: "LB", club: "Zamalek" },
          { name: "Mohamed Abdelmonem", pos: "CB", club: "Nice" },
          { name: "Ahmed Hegazi", pos: "CB", club: "Neom SC" },
          { name: "Mohamed Hany", pos: "RB", club: "Al Ahly" },
        ],
        [
          { name: "Marwan Attia", pos: "DM", club: "Al Ahly" },
          { name: "Emam Ashour", pos: "CM", club: "Al Ahly" },
        ],
        [
          { name: "Trezeguet", pos: "LW", club: "Trabzonspor" },
          { name: "Zizo", pos: "AM", club: "Al Ahly" },
          { name: "Mohamed Salah", pos: "RW", club: "Liverpool" },
        ],
        [{ name: "Omar Marmoush", pos: "ST", club: "Manchester City" }],
      ],
    },
    ec: {
      name: "Ecuador",
      formation: "4-2-3-1",
      rows: [
        [{ name: "Hernán Galíndez", pos: "GK", club: "Huracán" }],
        [
          { name: "Pervis Estupiñán", pos: "LB", club: "AC Milan" },
          { name: "Willian Pacho", pos: "CB", club: "Paris Saint-Germain" },
          { name: "Piero Hincapié", pos: "CB", club: "Arsenal" },
          { name: "Angelo Preciado", pos: "RB", club: "Sparta Prague" },
        ],
        [
          { name: "Moisés Caicedo", pos: "DM", club: "Chelsea" },
          { name: "Pedro Vite", pos: "CM", club: "Pumas UNAM" },
        ],
        [
          { name: "Nilson Angulo", pos: "LW", club: "Anderlecht" },
          { name: "Kendry Páez", pos: "AM", club: "Strasbourg" },
          { name: "Gonzalo Plata", pos: "RW", club: "Flamengo" },
        ],
        [{ name: "Enner Valencia", pos: "ST", club: "Pachuca" }],
      ],
    },
    ci: {
      name: "Ivory Coast",
      formation: "4-3-3",
      rows: [
        [{ name: "Yahia Fofana", pos: "GK", club: "Angers" }],
        [
          { name: "Ghislain Konan", pos: "LB", club: "Al-Fayha" },
          { name: "Evan Ndicka", pos: "CB", club: "Roma" },
          { name: "Ousmane Diomandé", pos: "CB", club: "Sporting CP" },
          { name: "Wilfried Singo", pos: "RB", club: "Galatasaray" },
        ],
        [
          { name: "Franck Kessié", pos: "CM", club: "Al-Ahli" },
          { name: "Ibrahim Sangaré", pos: "DM", club: "Nottingham Forest" },
          { name: "Seko Fofana", pos: "CM", club: "Rennes" },
        ],
        [
          { name: "Simon Adingra", pos: "LW", club: "Sunderland" },
          { name: "Sébastien Haller", pos: "ST", club: "Utrecht" },
          { name: "Amad Diallo", pos: "RW", club: "Manchester United" },
        ],
      ],
    },
    dk: {
      name: "Denmark",
      formation: "4-3-3",
      rows: [
        [{ name: "Kasper Schmeichel", pos: "GK", club: "Celtic" }],
        [
          { name: "Patrick Dorgu", pos: "LB", club: "Manchester United" },
          { name: "Andreas Christensen", pos: "CB", club: "Barcelona" },
          { name: "Joachim Andersen", pos: "CB", club: "Fulham" },
          { name: "Rasmus Kristensen", pos: "RB", club: "Eintracht Frankfurt" },
        ],
        [
          { name: "Pierre-Emile Højbjerg", pos: "CM", club: "Marseille" },
          { name: "Morten Hjulmand", pos: "DM", club: "Sporting CP" },
          { name: "Christian Eriksen", pos: "CM", club: "Wolfsburg" },
        ],
        [
          { name: "Mikkel Damsgaard", pos: "LW", club: "Brentford" },
          { name: "Rasmus Højlund", pos: "ST", club: "Napoli" },
          { name: "Gustav Isaksen", pos: "RW", club: "Lazio" },
        ],
      ],
    },
    cm: {
      name: "Cameroon",
      formation: "4-3-3",
      rows: [
        [{ name: "André Onana", pos: "GK", club: "Trabzonspor" }],
        [
          { name: "Nouhou Tolo", pos: "LB", club: "Seattle Sounders" },
          { name: "Jean-Charles Castelletto", pos: "CB", club: "Nantes" },
          { name: "Christopher Wooh", pos: "CB", club: "Rennes" },
          { name: "Junior Tchamadeu", pos: "RB", club: "Stoke City" },
        ],
        [
          { name: "Carlos Baleba", pos: "CM", club: "Brighton & Hove Albion" },
          { name: "André-Frank Zambo Anguissa", pos: "DM", club: "Napoli" },
          { name: "Martin Hongla", pos: "CM", club: "Espanyol" },
        ],
        [
          { name: "Moumi Ngamaleu", pos: "LW", club: "Dynamo Moscow" },
          { name: "Karl Etta Eyong", pos: "ST", club: "Levante" },
          { name: "Bryan Mbeumo", pos: "RW", club: "Manchester United" },
        ],
      ],
    },
    si: {
      name: "Slovenia",
      formation: "4-4-2",
      rows: [
        [{ name: "Jan Oblak", pos: "GK", club: "Atlético Madrid" }],
        [
          { name: "Erik Janža", pos: "LB", club: "Górnik Zabrze" },
          { name: "Jaka Bijol", pos: "CB", club: "Leeds United" },
          { name: "David Brekalo", pos: "CB", club: "Orlando City" },
          { name: "Žan Karničnik", pos: "RB", club: "Celje" },
        ],
        [
          { name: "Jan Mlakar", pos: "LM", club: "Pisa" },
          { name: "Timi Max Elšnik", pos: "CM", club: "Legia Warsaw" },
          { name: "Adam Gnezda Čerin", pos: "CM", club: "Panathinaikos" },
          { name: "Sandi Lovrić", pos: "RM", club: "Udinese" },
        ],
        [
          { name: "Benjamin Šeško", pos: "ST", club: "Manchester United" },
          { name: "Andraž Šporar", pos: "ST", club: "Slovan Bratislava" },
        ],
      ],
    },
    uy: {
      name: "Uruguay",
      formation: "4-3-3",
      rows: [
        [{ name: "Sergio Rochet", pos: "GK", club: "Internacional" }],
        [
          { name: "Matías Viña", pos: "LB", club: "Flamengo" },
          { name: "José María Giménez", pos: "CB", club: "Atlético Madrid" },
          { name: "Ronald Araújo", pos: "CB", club: "Barcelona" },
          { name: "Nahitan Nández", pos: "RB", club: "Al-Qadsiah" },
        ],
        [
          { name: "Rodrigo Bentancur", pos: "CM", club: "Tottenham Hotspur" },
          { name: "Manuel Ugarte", pos: "DM", club: "Manchester United" },
          { name: "Federico Valverde", pos: "CM", club: "Real Madrid" },
        ],
        [
          { name: "Maximiliano Araújo", pos: "LW", club: "Sporting CP" },
          { name: "Darwin Núñez", pos: "ST", club: "Al-Hilal" },
          { name: "Facundo Pellistri", pos: "RW", club: "Panathinaikos" },
        ],
      ],
    },
    gh: {
      name: "Ghana",
      formation: "4-2-3-1",
      rows: [
        [{ name: "Lawrence Ati-Zigi", pos: "GK", club: "St. Gallen" }],
        [
          { name: "Gideon Mensah", pos: "LB", club: "Auxerre" },
          { name: "Mohammed Salisu", pos: "CB", club: "Monaco" },
          { name: "Alexander Djiku", pos: "CB", club: "Spartak Moscow" },
          { name: "Tariq Lamptey", pos: "RB", club: "Fiorentina" },
        ],
        [
          { name: "Thomas Partey", pos: "DM", club: "Villarreal" },
          { name: "Salis Abdul Samed", pos: "CM", club: "Sunderland" },
        ],
        [
          { name: "Antoine Semenyo", pos: "LW", club: "Bournemouth" },
          { name: "Mohammed Kudus", pos: "AM", club: "Tottenham Hotspur" },
          { name: "Iñaki Williams", pos: "RW", club: "Athletic Club" },
        ],
        [{ name: "Jordan Ayew", pos: "ST", club: "Leicester City" }],
      ],
    },
    pl: {
      name: "Poland",
      formation: "3-5-2",
      rows: [
        [{ name: "Łukasz Skorupski", pos: "GK", club: "Bologna" }],
        [
          { name: "Jan Bednarek", pos: "CB", club: "Porto" },
          { name: "Jakub Kiwior", pos: "CB", club: "Porto" },
          { name: "Sebastian Walukiewicz", pos: "CB", club: "Torino" },
        ],
        [
          { name: "Nicola Zalewski", pos: "LWB", club: "Atalanta" },
          { name: "Piotr Zieliński", pos: "CM", club: "Inter Milan" },
          { name: "Bartosz Slisz", pos: "CM", club: "Atlanta United" },
          { name: "Sebastian Szymański", pos: "CM", club: "Fenerbahçe" },
          { name: "Przemysław Frankowski", pos: "RWB", club: "Galatasaray" },
        ],
        [
          { name: "Robert Lewandowski", pos: "ST", club: "Barcelona" },
          { name: "Karol Świderski", pos: "ST", club: "Panathinaikos" },
        ],
      ],
    },
    at: {
      name: "Austria",
      formation: "4-2-3-1",
      rows: [
        [{ name: "Patrick Pentz", pos: "GK", club: "Brøndby" }],
        [
          { name: "Phillipp Mwene", pos: "LB", club: "Mainz 05" },
          { name: "Kevin Danso", pos: "CB", club: "Tottenham Hotspur" },
          { name: "Philipp Lienhart", pos: "CB", club: "Freiburg" },
          { name: "Stefan Posch", pos: "RB", club: "Como" },
        ],
        [
          { name: "Nicolas Seiwald", pos: "DM", club: "RB Leipzig" },
          { name: "Xaver Schlager", pos: "CM", club: "RB Leipzig" },
        ],
        [
          { name: "Christoph Baumgartner", pos: "LW", club: "RB Leipzig" },
          { name: "Marcel Sabitzer", pos: "AM", club: "Borussia Dortmund" },
          { name: "Konrad Laimer", pos: "RW", club: "Bayern Munich" },
        ],
        [{ name: "Marko Arnautović", pos: "ST", club: "Red Star Belgrade" }],
      ],
    },
    co: {
      name: "Colombia",
      formation: "4-2-3-1",
      rows: [
        [{ name: "Camilo Vargas", pos: "GK", club: "Atlas" }],
        [
          { name: "Johan Mojica", pos: "LB", club: "Mallorca" },
          { name: "Jhon Lucumí", pos: "CB", club: "Bologna" },
          { name: "Davinson Sánchez", pos: "CB", club: "Galatasaray" },
          { name: "Daniel Muñoz", pos: "RB", club: "Crystal Palace" },
        ],
        [
          { name: "Richard Ríos", pos: "DM", club: "Benfica" },
          { name: "Jefferson Lerma", pos: "CM", club: "Crystal Palace" },
        ],
        [
          { name: "Luis Díaz", pos: "LW", club: "Bayern Munich" },
          { name: "James Rodríguez", pos: "AM", club: "Club León" },
          { name: "Jhon Arias", pos: "RW", club: "Wolves" },
        ],
        [{ name: "Jhon Córdoba", pos: "ST", club: "Krasnodar" }],
      ],
    },
    rs: {
      name: "Serbia",
      formation: "3-4-2-1",
      rows: [
        [{ name: "Đorđe Petrović", pos: "GK", club: "Bournemouth" }],
        [
          { name: "Strahinja Pavlović", pos: "CB", club: "AC Milan" },
          { name: "Miloš Veljković", pos: "CB", club: "Werder Bremen" },
          { name: "Nikola Milenković", pos: "CB", club: "Nottingham Forest" },
        ],
        [
          { name: "Filip Kostić", pos: "LWB", club: "Juventus" },
          { name: "Saša Lukić", pos: "CM", club: "Fulham" },
          { name: "Sergej Milinković-Savić", pos: "CM", club: "Al-Hilal" },
          { name: "Andrija Živković", pos: "RWB", club: "PAOK" },
        ],
        [
          { name: "Lazar Samardžić", pos: "AM", club: "Atalanta" },
          { name: "Luka Jović", pos: "AM", club: "AEK Athens" },
        ],
        [{ name: "Dušan Vlahović", pos: "ST", club: "Juventus" }],
      ],
    },
    us: {
      name: "United States",
      formation: "4-2-3-1",
      rows: [
        [{ name: "Matt Freese", pos: "GK", club: "New York City FC" }],
        [
          { name: "Antonee Robinson", pos: "LB", club: "Fulham" },
          { name: "Chris Richards", pos: "CB", club: "Crystal Palace" },
          { name: "Tim Ream", pos: "CB", club: "Charlotte FC" },
          { name: "Sergiño Dest", pos: "RB", club: "PSV Eindhoven" },
        ],
        [
          { name: "Tyler Adams", pos: "DM", club: "Bournemouth" },
          { name: "Weston McKennie", pos: "CM", club: "Juventus" },
        ],
        [
          { name: "Christian Pulisic", pos: "LW", club: "AC Milan" },
          { name: "Malik Tillman", pos: "AM", club: "Bayer Leverkusen" },
          { name: "Timothy Weah", pos: "RW", club: "Marseille" },
        ],
        [{ name: "Folarin Balogun", pos: "ST", club: "Monaco" }],
      ],
    },
    ch: {
      name: "Switzerland",
      formation: "4-2-3-1",
      rows: [
        [{ name: "Gregor Kobel", pos: "GK", club: "Borussia Dortmund" }],
        [
          { name: "Ricardo Rodríguez", pos: "LB", club: "Real Betis" },
          { name: "Manuel Akanji", pos: "CB", club: "Inter Milan" },
          { name: "Nico Elvedi", pos: "CB", club: "Borussia Mönchengladbach" },
          { name: "Silvan Widmer", pos: "RB", club: "Mainz 05" },
        ],
        [
          { name: "Granit Xhaka", pos: "DM", club: "Sunderland" },
          { name: "Remo Freuler", pos: "CM", club: "Bologna" },
        ],
        [
          { name: "Ruben Vargas", pos: "LW", club: "Sevilla" },
          { name: "Johan Manzambi", pos: "AM", club: "Freiburg" },
          { name: "Dan Ndoye", pos: "RW", club: "Nottingham Forest" },
        ],
        [{ name: "Breel Embolo", pos: "ST", club: "Rennes" }],
      ],
    },
    tr: {
      name: "Turkey",
      formation: "4-2-3-1",
      rows: [
        [{ name: "Uğurcan Çakır", pos: "GK", club: "Galatasaray" }],
        [
          { name: "Ferdi Kadıoğlu", pos: "LB", club: "Brighton & Hove Albion" },
          { name: "Abdülkerim Bardakcı", pos: "CB", club: "Galatasaray" },
          { name: "Merih Demiral", pos: "CB", club: "Al-Ahli" },
          { name: "Mert Müldür", pos: "RB", club: "Fenerbahçe" },
        ],
        [
          { name: "Hakan Çalhanoğlu", pos: "DM", club: "Inter Milan" },
          { name: "Orkun Kökçü", pos: "CM", club: "Beşiktaş" },
        ],
        [
          { name: "Kenan Yıldız", pos: "LW", club: "Juventus" },
          { name: "Arda Güler", pos: "AM", club: "Real Madrid" },
          { name: "Kerem Aktürkoğlu", pos: "RW", club: "Fenerbahçe" },
        ],
        [{ name: "Barış Alper Yılmaz", pos: "ST", club: "Galatasaray" }],
      ],
    },
    ma: {
      name: "Morocco",
      formation: "4-3-3",
      rows: [
        [{ name: "Yassine Bounou", pos: "GK", club: "Al-Hilal" }],
        [
          { name: "Noussair Mazraoui", pos: "LB", club: "Manchester United" },
          { name: "Nayef Aguerd", pos: "CB", club: "Marseille" },
          { name: "Abdelkabir Abqar", pos: "CB", club: "Alavés" },
          { name: "Achraf Hakimi", pos: "RB", club: "Paris Saint-Germain" },
        ],
        [
          { name: "Azzedine Ounahi", pos: "CM", club: "Girona" },
          { name: "Sofyan Amrabat", pos: "DM", club: "Real Betis" },
          { name: "Ismael Saibari", pos: "CM", club: "PSV Eindhoven" },
        ],
        [
          { name: "Abde Ezzalzouli", pos: "LW", club: "Real Betis" },
          { name: "Youssef En-Nesyri", pos: "ST", club: "Fenerbahçe" },
          { name: "Brahim Díaz", pos: "RW", club: "Real Madrid" },
        ],
      ],
    },
    ge: {
      name: "Georgia",
      formation: "4-2-3-1",
      rows: [
        [{ name: "Giorgi Mamardashvili", pos: "GK", club: "Liverpool" }],
        [
          { name: "Irakli Azarovi", pos: "LB", club: "Red Star Belgrade" },
          { name: "Lasha Dvali", pos: "CB", club: "APOEL" },
          { name: "Luka Lochoshvili", pos: "CB", club: "Cremonese" },
          { name: "Otar Kakabadze", pos: "RB", club: "Cracovia" },
        ],
        [
          { name: "Anzor Mekvabishvili", pos: "DM", club: "Universitatea Craiova" },
          { name: "Giorgi Kochorashvili", pos: "CM", club: "Sporting CP" },
        ],
        [
          { name: "Khvicha Kvaratskhelia", pos: "LW", club: "Paris Saint-Germain" },
          { name: "Otar Kiteishvili", pos: "AM", club: "Sturm Graz" },
          { name: "Zuriko Davitashvili", pos: "RW", club: "Saint-Étienne" },
        ],
        [{ name: "Georges Mikautadze", pos: "ST", club: "Villarreal" }],
      ],
    },
  },
};
