// Generated by scripts/fetch-seasons.mjs — do not edit by hand.
window.CLUB_SEASONS = {
 "Arsenal": {
  "league": "Premier League",
  "season": "2025-26",
  "pos": 1,
  "pts": 85,
  "w": 26,
  "d": 7,
  "l": 5,
  "gd": 44
 },
 "Manchester City": {
  "league": "Premier League",
  "season": "2025-26",
  "pos": 2,
  "pts": 78,
  "w": 23,
  "d": 9,
  "l": 6,
  "gd": 42
 },
 "Liverpool": {
  "league": "Premier League",
  "season": "2025-26",
  "pos": 5,
  "pts": 60,
  "w": 17,
  "d": 9,
  "l": 12,
  "gd": 10
 },
 "Chelsea": {
  "league": "Premier League",
  "season": "2025-26",
  "pos": 10,
  "pts": 52,
  "w": 14,
  "d": 10,
  "l": 14,
  "gd": 6
 },
 "Manchester United": {
  "league": "Premier League",
  "season": "2025-26",
  "pos": 3,
  "pts": 71,
  "w": 20,
  "d": 11,
  "l": 7,
  "gd": 19
 },
 "Tottenham Hotspur": {
  "league": "Premier League",
  "season": "2025-26",
  "pos": 17,
  "pts": 41,
  "w": 10,
  "d": 11,
  "l": 17,
  "gd": -9
 },
 "Aston Villa": {
  "league": "Premier League",
  "season": "2025-26",
  "pos": 4,
  "pts": 65,
  "w": 19,
  "d": 8,
  "l": 11,
  "gd": 7
 },
 "Sunderland": {
  "league": "Premier League",
  "season": "2025-26",
  "pos": 7,
  "pts": 54,
  "w": 14,
  "d": 12,
  "l": 12,
  "gd": -6
 },
 "Newcastle United": {
  "league": "Premier League",
  "season": "2025-26",
  "pos": 12,
  "pts": 49,
  "w": 14,
  "d": 7,
  "l": 17,
  "gd": -2
 },
 "Real Madrid": {
  "league": "LaLiga",
  "season": "2025-26",
  "pos": 2,
  "pts": 86,
  "w": 27,
  "d": 5,
  "l": 6,
  "gd": 42
 },
 "Barcelona": {
  "league": "LaLiga",
  "season": "2025-26",
  "pos": 1,
  "pts": 94,
  "w": 31,
  "d": 1,
  "l": 6,
  "gd": 59
 },
 "Atlético Madrid": {
  "league": "LaLiga",
  "season": "2025-26",
  "pos": 4,
  "pts": 69,
  "w": 21,
  "d": 6,
  "l": 11,
  "gd": 18
 },
 "Bayern Munich": {
  "league": "Bundesliga",
  "season": "2025-26",
  "pos": 1,
  "pts": 89,
  "w": 28,
  "d": 5,
  "l": 1,
  "gd": 86
 },
 "Inter Milan": {
  "league": "Serie A",
  "season": "2025-26",
  "pos": 1,
  "pts": 87,
  "w": 27,
  "d": 6,
  "l": 5,
  "gd": 54
 },
 "AC Milan": {
  "league": "Serie A",
  "season": "2025-26",
  "pos": 5,
  "pts": 70,
  "w": 20,
  "d": 10,
  "l": 8,
  "gd": 18
 },
 "Paris Saint-Germain": {
  "league": "Ligue 1",
  "season": "2025-26",
  "pos": 1,
  "pts": 76,
  "w": 24,
  "d": 4,
  "l": 6,
  "gd": 45
 }
};
