// Generated by scripts/fetch-wc.mjs — do not edit by hand.
window.WC = {
 "updated": "20260706",
 "players": {
  "César Montes": {
   "g": 0,
   "a": 0,
   "yc": 0,
   "rc": 1
  },
  "Raúl Jiménez": {
   "g": 2,
   "a": 0,
   "yc": 0,
   "rc": 0
  },
  "Malik Tillman": {
   "g": 1,
   "a": 1,
   "yc": 0,
   "rc": 0
  },
  "Tyler Adams": {
   "g": 0,
   "a": 0,
   "yc": 1,
   "rc": 0
  },
  "Folarin Balogun": {
   "g": 3,
   "a": 0,
   "yc": 1,
   "rc": 1
  },
  "Christian Pulisic": {
   "g": 0,
   "a": 1,
   "yc": 0,
   "rc": 0
  },
  "Breel Embolo": {
   "g": 2,
   "a": 2,
   "yc": 0,
   "rc": 0
  },
  "Bruno Guimarães": {
   "g": 0,
   "a": 4,
   "yc": 0,
   "rc": 0
  },
  "Casemiro": {
   "g": 1,
   "a": 0,
   "yc": 2,
   "rc": 0
  },
  "Vinícius Júnior": {
   "g": 4,
   "a": 1,
   "yc": 0,
   "rc": 0
  },
  "Ismael Saibari": {
   "g": 3,
   "a": 0,
   "yc": 0,
   "rc": 0
  },
  "Brahim Díaz": {
   "g": 0,
   "a": 4,
   "yc": 0,
   "rc": 0
  },
  "Aaron Hickey": {
   "g": 0,
   "a": 0,
   "yc": 1,
   "rc": 0
  },
  "John McGinn": {
   "g": 1,
   "a": 0,
   "yc": 0,
   "rc": 0
  },
  "Nico Schlotterbeck": {
   "g": 1,
   "a": 0,
   "yc": 0,
   "rc": 0
  },
  "Joshua Kimmich": {
   "g": 0,
   "a": 2,
   "yc": 0,
   "rc": 0
  },
  "Florian Wirtz": {
   "g": 0,
   "a": 3,
   "yc": 0,
   "rc": 0
  },
  "Deniz Undav": {
   "g": 3,
   "a": 2,
   "yc": 0,
   "rc": 0
  },
  "Virgil van Dijk": {
   "g": 1,
   "a": 1,
   "yc": 0,
   "rc": 0
  },
  "Micky van de Ven": {
   "g": 0,
   "a": 0,
   "yc": 1,
   "rc": 0
  },
  "Ryan Gravenberch": {
   "g": 0,
   "a": 2,
   "yc": 0,
   "rc": 0
  },
  "Crysencio Summerville": {
   "g": 2,
   "a": 2,
   "yc": 1,
   "rc": 0
  },
  "Wilfried Singo": {
   "g": 0,
   "a": 1,
   "yc": 0,
   "rc": 0
  },
  "Seko Fofana": {
   "g": 0,
   "a": 0,
   "yc": 1,
   "rc": 0
  },
  "Franck Kessié": {
   "g": 1,
   "a": 0,
   "yc": 1,
   "rc": 0
  },
  "Amad Diallo": {
   "g": 2,
   "a": 0,
   "yc": 0,
   "rc": 0
  },
  "Lucas Bergvall": {
   "g": 0,
   "a": 1,
   "yc": 1,
   "rc": 0
  },
  "Yasin Ayari": {
   "g": 2,
   "a": 0,
   "yc": 1,
   "rc": 0
  },
  "Alexander Isak": {
   "g": 1,
   "a": 3,
   "yc": 0,
   "rc": 0
  },
  "Viktor Gyökeres": {
   "g": 1,
   "a": 2,
   "yc": 1,
   "rc": 0
  },
  "Pedri": {
   "g": 0,
   "a": 0,
   "yc": 1,
   "rc": 0
  },
  "Timothy Castagne": {
   "g": 0,
   "a": 0,
   "yc": 1,
   "rc": 0
  },
  "Ahmed Fatouh": {
   "g": 0,
   "a": 0,
   "yc": 1,
   "rc": 0
  },
  "Mohamed Salah": {
   "g": 1,
   "a": 2,
   "yc": 0,
   "rc": 0
  },
  "Emam Ashour": {
   "g": 2,
   "a": 0,
   "yc": 0,
   "rc": 0
  },
  "Maximiliano Araújo": {
   "g": 2,
   "a": 1,
   "yc": 0,
   "rc": 0
  },
  "Adrien Rabiot": {
   "g": 0,
   "a": 1,
   "yc": 0,
   "rc": 0
  },
  "Kylian Mbappé": {
   "g": 7,
   "a": 2,
   "yc": 0,
   "rc": 0
  },
  "Michael Olise": {
   "g": 0,
   "a": 5,
   "yc": 1,
   "rc": 0
  },
  "David Møller Wolfe": {
   "g": 0,
   "a": 1,
   "yc": 0,
   "rc": 0
  },
  "Martin Ødegaard": {
   "g": 0,
   "a": 3,
   "yc": 0,
   "rc": 0
  },
  "Erling Haaland": {
   "g": 7,
   "a": 0,
   "yc": 0,
   "rc": 0
  },
  "Leo Østigård": {
   "g": 1,
   "a": 0,
   "yc": 0,
   "rc": 0
  },
  "Rodrigo De Paul": {
   "g": 0,
   "a": 1,
   "yc": 0,
   "rc": 0
  },
  "Lionel Messi": {
   "g": 7,
   "a": 0,
   "yc": 0,
   "rc": 0
  },
  "Xaver Schlager": {
   "g": 0,
   "a": 1,
   "yc": 0,
   "rc": 0
  },
  "Marcel Sabitzer": {
   "g": 1,
   "a": 0,
   "yc": 1,
   "rc": 0
  },
  "Marko Arnautović": {
   "g": 2,
   "a": 0,
   "yc": 1,
   "rc": 0
  },
  "João Neves": {
   "g": 1,
   "a": 0,
   "yc": 0,
   "rc": 0
  },
  "Pedro Neto": {
   "g": 0,
   "a": 1,
   "yc": 0,
   "rc": 0
  },
  "Bernardo Silva": {
   "g": 0,
   "a": 0,
   "yc": 1,
   "rc": 0
  },
  "Jude Bellingham": {
   "g": 2,
   "a": 1,
   "yc": 1,
   "rc": 0
  },
  "Declan Rice": {
   "g": 0,
   "a": 1,
   "yc": 1,
   "rc": 0
  },
  "Elliot Anderson": {
   "g": 0,
   "a": 1,
   "yc": 0,
   "rc": 0
  },
  "Harry Kane": {
   "g": 5,
   "a": 0,
   "yc": 0,
   "rc": 0
  },
  "Bukayo Saka": {
   "g": 0,
   "a": 2,
   "yc": 0,
   "rc": 0
  },
  "Ivan Perišić": {
   "g": 1,
   "a": 1,
   "yc": 2,
   "rc": 0
  },
  "Petar Sučić": {
   "g": 1,
   "a": 1,
   "yc": 1,
   "rc": 0
  },
  "Johan Mojica": {
   "g": 0,
   "a": 0,
   "yc": 1,
   "rc": 0
  },
  "Daniel Muñoz": {
   "g": 2,
   "a": 0,
   "yc": 0,
   "rc": 0
  },
  "Luis Díaz": {
   "g": 1,
   "a": 1,
   "yc": 0,
   "rc": 0
  },
  "Ruben Vargas": {
   "g": 2,
   "a": 1,
   "yc": 0,
   "rc": 0
  },
  "Johan Manzambi": {
   "g": 3,
   "a": 2,
   "yc": 0,
   "rc": 0
  },
  "Nico Elvedi": {
   "g": 0,
   "a": 0,
   "yc": 1,
   "rc": 0
  },
  "Granit Xhaka": {
   "g": 1,
   "a": 0,
   "yc": 1,
   "rc": 0
  },
  "Chris Richards": {
   "g": 0,
   "a": 0,
   "yc": 1,
   "rc": 0
  },
  "Antonee Robinson": {
   "g": 0,
   "a": 0,
   "yc": 1,
   "rc": 0
  },
  "Andy Robertson": {
   "g": 0,
   "a": 0,
   "yc": 1,
   "rc": 0
  },
  "Matheus Cunha": {
   "g": 3,
   "a": 0,
   "yc": 0,
   "rc": 0
  },
  "Denzel Dumfries": {
   "g": 0,
   "a": 2,
   "yc": 0,
   "rc": 0
  },
  "Brian Brobbey": {
   "g": 3,
   "a": 0,
   "yc": 0,
   "rc": 0
  },
  "Cody Gakpo": {
   "g": 3,
   "a": 1,
   "yc": 0,
   "rc": 0
  },
  "Anthony Elanga": {
   "g": 2,
   "a": 0,
   "yc": 0,
   "rc": 0
  },
  "Gabriel Gudmundsson": {
   "g": 0,
   "a": 0,
   "yc": 1,
   "rc": 0
  },
  "Dani Olmo": {
   "g": 0,
   "a": 1,
   "yc": 0,
   "rc": 0
  },
  "Mikel Oyarzabal": {
   "g": 4,
   "a": 1,
   "yc": 0,
   "rc": 0
  },
  "Lamine Yamal": {
   "g": 1,
   "a": 0,
   "yc": 0,
   "rc": 0
  },
  "Romelu Lukaku": {
   "g": 2,
   "a": 1,
   "yc": 1,
   "rc": 0
  },
  "Rodrigo Bentancur": {
   "g": 0,
   "a": 0,
   "yc": 1,
   "rc": 0
  },
  "Mohamed Hany": {
   "g": 0,
   "a": 1,
   "yc": 0,
   "rc": 0
  },
  "Trezeguet": {
   "g": 1,
   "a": 1,
   "yc": 0,
   "rc": 0
  },
  "Konrad Laimer": {
   "g": 0,
   "a": 1,
   "yc": 1,
   "rc": 0
  },
  "Stefan Posch": {
   "g": 0,
   "a": 0,
   "yc": 2,
   "rc": 0
  },
  "Ousmane Dembélé": {
   "g": 4,
   "a": 2,
   "yc": 0,
   "rc": 0
  },
  "Sadio Mané": {
   "g": 0,
   "a": 1,
   "yc": 0,
   "rc": 0
  },
  "Ismaïla Sarr": {
   "g": 4,
   "a": 1,
   "yc": 0,
   "rc": 0
  },
  "Nuno Mendes": {
   "g": 1,
   "a": 0,
   "yc": 0,
   "rc": 0
  },
  "João Cancelo": {
   "g": 0,
   "a": 1,
   "yc": 0,
   "rc": 0
  },
  "Bruno Fernandes": {
   "g": 0,
   "a": 1,
   "yc": 0,
   "rc": 0
  },
  "Cristiano Ronaldo": {
   "g": 3,
   "a": 0,
   "yc": 0,
   "rc": 0
  },
  "Rafael Leão": {
   "g": 1,
   "a": 1,
   "yc": 0,
   "rc": 0
  },
  "Iñaki Williams": {
   "g": 0,
   "a": 0,
   "yc": 1,
   "rc": 0
  },
  "Josip Stanišić": {
   "g": 0,
   "a": 1,
   "yc": 0,
   "rc": 0
  },
  "Ante Budimir": {
   "g": 1,
   "a": 0,
   "yc": 0,
   "rc": 0
  },
  "Jhon Lucumí": {
   "g": 0,
   "a": 0,
   "yc": 1,
   "rc": 0
  },
  "Jefferson Lerma": {
   "g": 0,
   "a": 0,
   "yc": 1,
   "rc": 0
  },
  "Achraf Hakimi": {
   "g": 1,
   "a": 2,
   "yc": 1,
   "rc": 0
  },
  "Jorge Sánchez": {
   "g": 0,
   "a": 1,
   "yc": 0,
   "rc": 0
  },
  "Edson Álvarez": {
   "g": 0,
   "a": 0,
   "yc": 1,
   "rc": 0
  },
  "Ibrahim Sangaré": {
   "g": 0,
   "a": 1,
   "yc": 0,
   "rc": 0
  },
  "Piero Hincapié": {
   "g": 0,
   "a": 0,
   "yc": 1,
   "rc": 1
  },
  "Pedro Vite": {
   "g": 0,
   "a": 1,
   "yc": 0,
   "rc": 0
  },
  "Nilson Angulo": {
   "g": 1,
   "a": 0,
   "yc": 0,
   "rc": 0
  },
  "Gonzalo Plata": {
   "g": 1,
   "a": 0,
   "yc": 1,
   "rc": 0
  },
  "Aleksandar Pavlović": {
   "g": 0,
   "a": 0,
   "yc": 1,
   "rc": 0
  },
  "Leroy Sané": {
   "g": 1,
   "a": 0,
   "yc": 0,
   "rc": 0
  },
  "Isak Hien": {
   "g": 0,
   "a": 0,
   "yc": 1,
   "rc": 0
  },
  "Tijjani Reijnders": {
   "g": 0,
   "a": 1,
   "yc": 0,
   "rc": 0
  },
  "Orkun Kökçü": {
   "g": 0,
   "a": 1,
   "yc": 0,
   "rc": 0
  },
  "Barış Alper Yılmaz": {
   "g": 1,
   "a": 1,
   "yc": 0,
   "rc": 0
  },
  "Arda Güler": {
   "g": 1,
   "a": 0,
   "yc": 0,
   "rc": 0
  },
  "Thelo Aasgaard": {
   "g": 1,
   "a": 0,
   "yc": 0,
   "rc": 0
  },
  "Aurélien Tchouaméni": {
   "g": 0,
   "a": 1,
   "yc": 1,
   "rc": 0
  },
  "Désiré Doué": {
   "g": 1,
   "a": 0,
   "yc": 0,
   "rc": 0
  },
  "Habib Diarra": {
   "g": 2,
   "a": 0,
   "yc": 0,
   "rc": 0
  },
  "Álex Baena": {
   "g": 1,
   "a": 1,
   "yc": 1,
   "rc": 0
  },
  "Kevin De Bruyne": {
   "g": 1,
   "a": 0,
   "yc": 0,
   "rc": 0
  },
  "Leandro Trossard": {
   "g": 2,
   "a": 1,
   "yc": 0,
   "rc": 0
  },
  "Alexis Saelemaekers": {
   "g": 1,
   "a": 0,
   "yc": 0,
   "rc": 0
  },
  "Mateo Kovačić": {
   "g": 0,
   "a": 1,
   "yc": 0,
   "rc": 0
  },
  "Luka Modrić": {
   "g": 0,
   "a": 1,
   "yc": 1,
   "rc": 0
  },
  "Lautaro Martínez": {
   "g": 1,
   "a": 0,
   "yc": 0,
   "rc": 0
  },
  "Gabriel Magalhães": {
   "g": 0,
   "a": 1,
   "yc": 0,
   "rc": 0
  },
  "Chemsdine Talbi": {
   "g": 0,
   "a": 1,
   "yc": 0,
   "rc": 0
  },
  "Antonio Nusa": {
   "g": 1,
   "a": 0,
   "yc": 1,
   "rc": 0
  },
  "Moisés Caicedo": {
   "g": 0,
   "a": 0,
   "yc": 1,
   "rc": 0
  },
  "Kendry Páez": {
   "g": 0,
   "a": 0,
   "yc": 1,
   "rc": 0
  },
  "Anthony Gordon": {
   "g": 0,
   "a": 2,
   "yc": 0,
   "rc": 0
  },
  "Youri Tielemans": {
   "g": 2,
   "a": 0,
   "yc": 0,
   "rc": 0
  },
  "Moussa Niakhaté": {
   "g": 0,
   "a": 1,
   "yc": 0,
   "rc": 0
  },
  "Marc Cucurella": {
   "g": 0,
   "a": 2,
   "yc": 0,
   "rc": 0
  },
  "Pedro Porro": {
   "g": 1,
   "a": 0,
   "yc": 0,
   "rc": 0
  },
  "Rúben Dias": {
   "g": 0,
   "a": 0,
   "yc": 1,
   "rc": 0
  },
  "Dan Ndoye": {
   "g": 1,
   "a": 0,
   "yc": 0,
   "rc": 0
  },
  "Alexis Mac Allister": {
   "g": 0,
   "a": 1,
   "yc": 0,
   "rc": 0
  },
  "Jhon Arias": {
   "g": 1,
   "a": 0,
   "yc": 1,
   "rc": 0
  },
  "Richard Ríos": {
   "g": 0,
   "a": 0,
   "yc": 1,
   "rc": 0
  },
  "Azzedine Ounahi": {
   "g": 2,
   "a": 0,
   "yc": 1,
   "rc": 0
  },
  "Manu Koné": {
   "g": 0,
   "a": 0,
   "yc": 1,
   "rc": 0
  }
 },
 "nations": {
  "gb-eng": "active",
  "fr": "active",
  "br": "out",
  "es": "active",
  "nl": "out",
  "pt": "active",
  "ar": "active",
  "be": "active",
  "it": "nq",
  "no": "active",
  "se": "out",
  "hr": "out",
  "hu": "nq",
  "gb-nir": "nq",
  "de": "out",
  "eg": "active",
  "ec": "out",
  "ci": "out",
  "dk": "nq",
  "cm": "nq",
  "si": "nq",
  "uy": "out",
  "gh": "out",
  "pl": "nq",
  "at": "out",
  "co": "active",
  "rs": "nq",
  "us": "active",
  "ch": "active",
  "tr": "out",
  "ma": "active",
  "ge": "nq",
  "gb-sct": "out",
  "sn": "out",
  "mx": "active"
 },
 "nationsInfo": {
  "gb-eng": {
   "w": 3,
   "d": 0,
   "l": 1,
   "gf": 8,
   "ga": 3,
   "lastRound": "the Round of 32",
   "next": {
    "opp": "Mexico",
    "date": "2026-07-06",
    "round": "the Round of 16"
   },
   "out": null
  },
  "fr": {
   "w": 5,
   "d": 0,
   "l": 0,
   "gf": 14,
   "ga": 2,
   "lastRound": "the Round of 16",
   "next": {
    "opp": "Morocco",
    "date": "2026-07-09",
    "round": "the quarterfinals"
   },
   "out": null
  },
  "br": {
   "w": 3,
   "d": 0,
   "l": 2,
   "gf": 10,
   "ga": 4,
   "lastRound": "the Round of 16",
   "next": null,
   "out": {
    "round": "the Round of 16",
    "by": "Norway"
   }
  },
  "es": {
   "w": 3,
   "d": 0,
   "l": 1,
   "gf": 8,
   "ga": 0,
   "lastRound": "the Round of 32",
   "next": {
    "opp": "Portugal",
    "date": "2026-07-06",
    "round": "the Round of 16"
   },
   "out": null
  },
  "nl": {
   "w": 2,
   "d": 0,
   "l": 2,
   "gf": 11,
   "ga": 5,
   "lastRound": "the Round of 32",
   "next": null,
   "out": {
    "round": "the Round of 32",
    "by": "Morocco"
   }
  },
  "pt": {
   "w": 2,
   "d": 0,
   "l": 2,
   "gf": 8,
   "ga": 2,
   "lastRound": "the Round of 32",
   "next": {
    "opp": "Spain",
    "date": "2026-07-06",
    "round": "the Round of 16"
   },
   "out": null
  },
  "ar": {
   "w": 4,
   "d": 0,
   "l": 0,
   "gf": 11,
   "ga": 3,
   "lastRound": "the Round of 32",
   "next": {
    "opp": "Egypt",
    "date": "2026-07-07",
    "round": "the Round of 16"
   },
   "out": null
  },
  "be": {
   "w": 2,
   "d": 0,
   "l": 2,
   "gf": 9,
   "ga": 4,
   "lastRound": "the Round of 32",
   "next": {
    "opp": "United States",
    "date": "2026-07-07",
    "round": "the Round of 16"
   },
   "out": null
  },
  "no": {
   "w": 4,
   "d": 0,
   "l": 1,
   "gf": 12,
   "ga": 9,
   "lastRound": "the Round of 16",
   "next": {
    "opp": "Round of 16 4 Winner",
    "date": "2026-07-11",
    "round": "the quarterfinals"
   },
   "out": null
  },
  "se": {
   "w": 1,
   "d": 0,
   "l": 3,
   "gf": 7,
   "ga": 10,
   "lastRound": "the Round of 32",
   "next": null,
   "out": {
    "round": "the Round of 32",
    "by": "France"
   }
  },
  "hr": {
   "w": 2,
   "d": 0,
   "l": 2,
   "gf": 6,
   "ga": 7,
   "lastRound": "the Round of 32",
   "next": null,
   "out": {
    "round": "the Round of 32",
    "by": "Portugal"
   }
  },
  "de": {
   "w": 2,
   "d": 0,
   "l": 2,
   "gf": 11,
   "ga": 5,
   "lastRound": "the Round of 32",
   "next": null,
   "out": {
    "round": "the Round of 32",
    "by": "Paraguay"
   }
  },
  "eg": {
   "w": 2,
   "d": 0,
   "l": 2,
   "gf": 6,
   "ga": 4,
   "lastRound": "the Round of 32",
   "next": {
    "opp": "Argentina",
    "date": "2026-07-07",
    "round": "the Round of 16"
   },
   "out": null
  },
  "ec": {
   "w": 1,
   "d": 0,
   "l": 3,
   "gf": 2,
   "ga": 4,
   "lastRound": "the Round of 32",
   "next": null,
   "out": {
    "round": "the Round of 32",
    "by": "Mexico"
   }
  },
  "ci": {
   "w": 2,
   "d": 0,
   "l": 2,
   "gf": 5,
   "ga": 4,
   "lastRound": "the Round of 32",
   "next": null,
   "out": {
    "round": "the Round of 32",
    "by": "Norway"
   }
  },
  "uy": {
   "w": 0,
   "d": 0,
   "l": 3,
   "gf": 3,
   "ga": 4,
   "lastRound": "the group stage",
   "next": null,
   "out": null
  },
  "gh": {
   "w": 1,
   "d": 0,
   "l": 3,
   "gf": 2,
   "ga": 3,
   "lastRound": "the Round of 32",
   "next": null,
   "out": {
    "round": "the Round of 32",
    "by": "Colombia"
   }
  },
  "at": {
   "w": 1,
   "d": 0,
   "l": 3,
   "gf": 6,
   "ga": 9,
   "lastRound": "the Round of 32",
   "next": null,
   "out": {
    "round": "the Round of 32",
    "by": "Spain"
   }
  },
  "co": {
   "w": 3,
   "d": 0,
   "l": 1,
   "gf": 5,
   "ga": 1,
   "lastRound": "the Round of 32",
   "next": {
    "opp": "Switzerland",
    "date": "2026-07-07",
    "round": "the Round of 16"
   },
   "out": null
  },
  "us": {
   "w": 3,
   "d": 0,
   "l": 1,
   "gf": 10,
   "ga": 4,
   "lastRound": "the Round of 32",
   "next": {
    "opp": "Belgium",
    "date": "2026-07-07",
    "round": "the Round of 16"
   },
   "out": null
  },
  "ch": {
   "w": 3,
   "d": 0,
   "l": 1,
   "gf": 9,
   "ga": 3,
   "lastRound": "the Round of 32",
   "next": {
    "opp": "Colombia",
    "date": "2026-07-07",
    "round": "the Round of 16"
   },
   "out": null
  },
  "tr": {
   "w": 1,
   "d": 0,
   "l": 2,
   "gf": 3,
   "ga": 5,
   "lastRound": "the group stage",
   "next": null,
   "out": null
  },
  "ma": {
   "w": 4,
   "d": 0,
   "l": 1,
   "gf": 10,
   "ga": 4,
   "lastRound": "the Round of 16",
   "next": {
    "opp": "France",
    "date": "2026-07-09",
    "round": "the quarterfinals"
   },
   "out": null
  },
  "gb-sct": {
   "w": 1,
   "d": 0,
   "l": 2,
   "gf": 1,
   "ga": 4,
   "lastRound": "the group stage",
   "next": null,
   "out": null
  },
  "sn": {
   "w": 1,
   "d": 0,
   "l": 3,
   "gf": 10,
   "ga": 9,
   "lastRound": "the Round of 32",
   "next": null,
   "out": {
    "round": "the Round of 32",
    "by": "Belgium"
   }
  },
  "mx": {
   "w": 4,
   "d": 0,
   "l": 0,
   "gf": 8,
   "ga": 0,
   "lastRound": "the Round of 32",
   "next": {
    "opp": "England",
    "date": "2026-07-06",
    "round": "the Round of 16"
   },
   "out": null
  }
 },
 "bench": {
  "mx": [
   {
    "name": "Julián Quiñones",
    "g": 3,
    "a": 1,
    "yc": 0,
    "rc": 0
   },
   {
    "name": "Roberto Alvarado",
    "g": 0,
    "a": 3,
    "yc": 0,
    "rc": 0
   },
   {
    "name": "Luis Romo",
    "g": 1,
    "a": 1,
    "yc": 0,
    "rc": 0
   },
   {
    "name": "Érik Lira",
    "g": 0,
    "a": 1,
    "yc": 0,
    "rc": 0
   },
   {
    "name": "Mateo Chávez",
    "g": 1,
    "a": 0,
    "yc": 0,
    "rc": 0
   },
   {
    "name": "Álvaro Fidalgo",
    "g": 1,
    "a": 0,
    "yc": 0,
    "rc": 0
   }
  ],
  "us": [
   {
    "name": "Alex Freeman",
    "g": 1,
    "a": 1,
    "yc": 0,
    "rc": 0
   },
   {
    "name": "Sebastian Berhalter",
    "g": 1,
    "a": 1,
    "yc": 1,
    "rc": 0
   },
   {
    "name": "Giovanni Reyna",
    "g": 1,
    "a": 0,
    "yc": 0,
    "rc": 0
   },
   {
    "name": "Auston Trusty",
    "g": 1,
    "a": 0,
    "yc": 0,
    "rc": 0
   }
  ],
  "de": [
   {
    "name": "Kai Havertz",
    "g": 3,
    "a": 0,
    "yc": 1,
    "rc": 0
   },
   {
    "name": "Nathaniel Brown",
    "g": 1,
    "a": 1,
    "yc": 0,
    "rc": 0
   },
   {
    "name": "Felix Nmecha",
    "g": 1,
    "a": 1,
    "yc": 0,
    "rc": 0
   },
   {
    "name": "Jamal Musiala",
    "g": 1,
    "a": 0,
    "yc": 1,
    "rc": 0
   },
   {
    "name": "Nadiem Amiri",
    "g": 0,
    "a": 1,
    "yc": 0,
    "rc": 0
   }
  ],
  "nl": [
   {
    "name": "Memphis Depay",
    "g": 0,
    "a": 1,
    "yc": 1,
    "rc": 0
   },
   {
    "name": "Jan Paul van Hecke",
    "g": 1,
    "a": 0,
    "yc": 0,
    "rc": 0
   }
  ],
  "se": [
   {
    "name": "Mattias Svanberg",
    "g": 1,
    "a": 0,
    "yc": 0,
    "rc": 0
   }
  ],
  "fr": [
   {
    "name": "Bradley Barcola",
    "g": 2,
    "a": 1,
    "yc": 1,
    "rc": 0
   },
   {
    "name": "Désiré Doué",
    "g": 1,
    "a": 0,
    "yc": 0,
    "rc": 0
   }
  ],
  "sn": [
   {
    "name": "Iliman Ndiaye",
    "g": 1,
    "a": 2,
    "yc": 0,
    "rc": 0
   },
   {
    "name": "Pape Gueye",
    "g": 2,
    "a": 1,
    "yc": 1,
    "rc": 0
   },
   {
    "name": "Ibrahim Mbaye",
    "g": 1,
    "a": 0,
    "yc": 0,
    "rc": 0
   },
   {
    "name": "Nicolas Jackson",
    "g": 0,
    "a": 1,
    "yc": 0,
    "rc": 0
   },
   {
    "name": "Abdoulaye Seck",
    "g": 0,
    "a": 1,
    "yc": 1,
    "rc": 0
   },
   {
    "name": "Lamine Camara",
    "g": 0,
    "a": 1,
    "yc": 1,
    "rc": 0
   }
  ],
  "ar": [
   {
    "name": "Lisandro Martínez",
    "g": 1,
    "a": 1,
    "yc": 0,
    "rc": 0
   },
   {
    "name": "Nico González",
    "g": 0,
    "a": 1,
    "yc": 0,
    "rc": 0
   },
   {
    "name": "Facundo Medina",
    "g": 0,
    "a": 1,
    "yc": 1,
    "rc": 0
   },
   {
    "name": "Giovani Lo Celso",
    "g": 1,
    "a": 0,
    "yc": 0,
    "rc": 0
   },
   {
    "name": "Lautaro Martínez",
    "g": 1,
    "a": 0,
    "yc": 0,
    "rc": 0
   }
  ],
  "at": [
   {
    "name": "Romano Schmid",
    "g": 1,
    "a": 0,
    "yc": 0,
    "rc": 0
   },
   {
    "name": "David Alaba",
    "g": 0,
    "a": 1,
    "yc": 0,
    "rc": 0
   },
   {
    "name": "Sasa Kalajdzic",
    "g": 1,
    "a": 0,
    "yc": 0,
    "rc": 0
   },
   {
    "name": "Michael Gregoritsch",
    "g": 0,
    "a": 1,
    "yc": 0,
    "rc": 0
   }
  ],
  "gb-eng": [
   {
    "name": "Marcus Rashford",
    "g": 1,
    "a": 0,
    "yc": 0,
    "rc": 0
   }
  ],
  "hr": [
   {
    "name": "Petar Musa",
    "g": 1,
    "a": 0,
    "yc": 0,
    "rc": 0
   },
   {
    "name": "Martin Baturina",
    "g": 1,
    "a": 0,
    "yc": 0,
    "rc": 0
   },
   {
    "name": "Nikola Vlasic",
    "g": 1,
    "a": 0,
    "yc": 0,
    "rc": 0
   }
  ],
  "gh": [
   {
    "name": "Caleb Yirenkyi",
    "g": 1,
    "a": 0,
    "yc": 2,
    "rc": 0
   },
   {
    "name": "Brandon Thomas-Asante",
    "g": 0,
    "a": 1,
    "yc": 0,
    "rc": 0
   },
   {
    "name": "Derrick Luckassen",
    "g": 1,
    "a": 0,
    "yc": 0,
    "rc": 0
   },
   {
    "name": "Ernest Nuamah",
    "g": 0,
    "a": 1,
    "yc": 0,
    "rc": 0
   }
  ],
  "co": [
   {
    "name": "Gustavo Puerta",
    "g": 0,
    "a": 1,
    "yc": 1,
    "rc": 0
   },
   {
    "name": "Jáminton Campaz",
    "g": 1,
    "a": 0,
    "yc": 0,
    "rc": 0
   },
   {
    "name": "Cucho Hernández",
    "g": 0,
    "a": 1,
    "yc": 0,
    "rc": 0
   },
   {
    "name": "Juan Fernando Quintero",
    "g": 0,
    "a": 1,
    "yc": 0,
    "rc": 0
   },
   {
    "name": "Luis Suárez",
    "g": 0,
    "a": 1,
    "yc": 0,
    "rc": 0
   }
  ],
  "ma": [
   {
    "name": "Soufiane Rahimi",
    "g": 2,
    "a": 1,
    "yc": 0,
    "rc": 0
   },
   {
    "name": "Issa Diop",
    "g": 1,
    "a": 0,
    "yc": 2,
    "rc": 0
   },
   {
    "name": "Chadi Riad",
    "g": 0,
    "a": 1,
    "yc": 0,
    "rc": 0
   },
   {
    "name": "Gessime Yassine",
    "g": 1,
    "a": 0,
    "yc": 0,
    "rc": 0
   },
   {
    "name": "Chemsdine Talbi",
    "g": 0,
    "a": 1,
    "yc": 0,
    "rc": 0
   }
  ],
  "br": [
   {
    "name": "Lucas Paquetá",
    "g": 0,
    "a": 1,
    "yc": 0,
    "rc": 0
   },
   {
    "name": "Rayan",
    "g": 0,
    "a": 1,
    "yc": 0,
    "rc": 0
   },
   {
    "name": "Gabriel Martinelli",
    "g": 1,
    "a": 0,
    "yc": 0,
    "rc": 0
   },
   {
    "name": "Neymar",
    "g": 1,
    "a": 0,
    "yc": 1,
    "rc": 0
   }
  ],
  "es": [
   {
    "name": "Álex Baena",
    "g": 1,
    "a": 1,
    "yc": 1,
    "rc": 0
   },
   {
    "name": "Aymeric Laporte",
    "g": 0,
    "a": 1,
    "yc": 0,
    "rc": 0
   },
   {
    "name": "Dani Olmo",
    "g": 0,
    "a": 1,
    "yc": 0,
    "rc": 0
   },
   {
    "name": "Marcos Llorente",
    "g": 0,
    "a": 1,
    "yc": 0,
    "rc": 0
   }
  ],
  "uy": [
   {
    "name": "Agustín Canobbio",
    "g": 1,
    "a": 0,
    "yc": 0,
    "rc": 1
   }
  ],
  "eg": [
   {
    "name": "Mostafa Zico",
    "g": 1,
    "a": 1,
    "yc": 0,
    "rc": 0
   },
   {
    "name": "Mahmoud Saber",
    "g": 1,
    "a": 0,
    "yc": 1,
    "rc": 0
   },
   {
    "name": "Karim Hafez",
    "g": 0,
    "a": 1,
    "yc": 0,
    "rc": 0
   }
  ],
  "no": [
   {
    "name": "Andreas Schjelderup",
    "g": 0,
    "a": 3,
    "yc": 0,
    "rc": 0
   },
   {
    "name": "Patrick Berg",
    "g": 0,
    "a": 2,
    "yc": 1,
    "rc": 0
   },
   {
    "name": "Marcus Holmgren Pedersen",
    "g": 1,
    "a": 0,
    "yc": 0,
    "rc": 0
   }
  ],
  "pt": [
   {
    "name": "Rafael Leão",
    "g": 1,
    "a": 1,
    "yc": 0,
    "rc": 0
   },
   {
    "name": "Gonçalo Ramos",
    "g": 1,
    "a": 0,
    "yc": 0,
    "rc": 0
   }
  ],
  "ci": [
   {
    "name": "Nicolas Pépé",
    "g": 2,
    "a": 1,
    "yc": 1,
    "rc": 0
   },
   {
    "name": "Yan Diomande",
    "g": 0,
    "a": 1,
    "yc": 0,
    "rc": 0
   }
  ],
  "ec": [
   {
    "name": "Kevin Rodríguez",
    "g": 0,
    "a": 1,
    "yc": 0,
    "rc": 0
   }
  ],
  "tr": [
   {
    "name": "Kaan Ayhan",
    "g": 1,
    "a": 0,
    "yc": 0,
    "rc": 0
   }
  ],
  "be": [
   {
    "name": "Hans Vanaken",
    "g": 0,
    "a": 1,
    "yc": 0,
    "rc": 0
   },
   {
    "name": "Alexis Saelemaekers",
    "g": 1,
    "a": 0,
    "yc": 0,
    "rc": 0
   },
   {
    "name": "Nicolas Raskin",
    "g": 0,
    "a": 1,
    "yc": 0,
    "rc": 0
   },
   {
    "name": "Thomas Meunier",
    "g": 0,
    "a": 1,
    "yc": 0,
    "rc": 0
   }
  ]
 },
 "squads": {
  "gb-eng": [
   "Anthony Gordon",
   "Bukayo Saka",
   "Dan Burn",
   "Dean Henderson",
   "Declan Rice",
   "Djed Spence",
   "Eberechi Eze",
   "Elliot Anderson",
   "Ezri Konsa",
   "Harry Kane",
   "Ivan Toney",
   "James Trafford",
   "Jarell Quansah",
   "John Stones",
   "Jordan Henderson",
   "Jordan Pickford",
   "Jude Bellingham",
   "Kobbie Mainoo",
   "Marc Guéhi",
   "Marcus Rashford",
   "Morgan Rogers",
   "Nico O'Reilly",
   "Noni Madueke",
   "Ollie Watkins",
   "Reece James",
   "Trevoh Chalobah"
  ],
  "fr": [
   "Adrien Rabiot",
   "Aurélien Tchouaméni",
   "Bradley Barcola",
   "Brice Samba",
   "Dayot Upamecano",
   "Désiré Doué",
   "Ibrahima Konaté",
   "Jean-Philippe Mateta",
   "Jules Koundé",
   "Kylian Mbappé",
   "Lucas Digne",
   "Lucas Hernández",
   "Maghnes Akliouche",
   "Malo Gusto",
   "Manu Koné",
   "Marcus Thuram",
   "Maxence Lacroix",
   "Michael Olise",
   "Mike Maignan",
   "N'Golo Kanté",
   "Ousmane Dembélé",
   "Rayan Cherki",
   "Robin Risser",
   "Théo Hernandez",
   "Warren Zaïre-Emery",
   "William Saliba"
  ],
  "br": [
   "Alex Sandro",
   "Alisson Becker",
   "Bremer",
   "Bruno Guimarães",
   "Casemiro",
   "Danilo",
   "Danilo Santos",
   "Douglas Santos",
   "Ederson",
   "Endrick",
   "Fabinho",
   "Gabriel Magalhães",
   "Gabriel Martinelli",
   "Igor Thiago",
   "Lucas Paquetá",
   "Luiz Henrique",
   "Léo Pereira",
   "Marquinhos",
   "Matheus Cunha",
   "Neymar",
   "Raphinha",
   "Rayan",
   "Roger Ibañez",
   "Vinícius Júnior",
   "Weverton",
   "Éderson"
  ],
  "es": [
   "Alejandro Grimaldo",
   "Aymeric Laporte",
   "Borja Iglesias",
   "Dani Olmo",
   "David Raya",
   "Eric García",
   "Fabián Ruiz",
   "Ferran Torres",
   "Gavi",
   "Joan García",
   "Lamine Yamal",
   "Marc Cucurella",
   "Marc Pubill",
   "Marcos Llorente",
   "Martín Zubimendi",
   "Mikel Merino",
   "Mikel Oyarzabal",
   "Nico Williams",
   "Pau Cubarsí",
   "Pedri",
   "Pedro Porro",
   "Rodri",
   "Unai Simón",
   "Víctor Muñoz",
   "Yéremy Pino",
   "Álex Baena"
  ],
  "nl": [
   "Bart Verbruggen",
   "Brian Brobbey",
   "Cody Gakpo",
   "Crysencio Summerville",
   "Denzel Dumfries",
   "Donyell Malen",
   "Frenkie de Jong",
   "Guus Til",
   "Jan Paul van Hecke",
   "Jorrel Hato",
   "Justin Kluivert",
   "Lutsharel Geertruida",
   "Mark Flekken",
   "Marten de Roon",
   "Mats Wieffer",
   "Memphis Depay",
   "Micky van de Ven",
   "Nathan Aké",
   "Noa Lang",
   "Quinten Timber",
   "Robin Roefs",
   "Ryan Gravenberch",
   "Teun Koopmeiners",
   "Tijjani Reijnders",
   "Virgil van Dijk",
   "Wout Weghorst"
  ],
  "pt": [
   "Bernardo Silva",
   "Bruno Fernandes",
   "Cristiano Ronaldo",
   "Diogo Costa",
   "Diogo Dalot",
   "Francisco Conceição",
   "Francisco Trincão",
   "Gonçalo Guedes",
   "Gonçalo Inácio",
   "Gonçalo Ramos",
   "José Sá",
   "João Cancelo",
   "João Félix",
   "João Neves",
   "Matheus Nunes",
   "Nuno Mendes",
   "Nélson Semedo",
   "Pedro Neto",
   "Rafael Leão",
   "Renato Veiga",
   "Rui Silva",
   "Rúben Dias",
   "Rúben Neves",
   "Samú Costa",
   "Tomás Araújo",
   "Vitinha"
  ],
  "ar": [
   "Alexis Mac Allister",
   "Cristian Romero",
   "Emiliano Martínez",
   "Enzo Fernández",
   "Exequiel Palacios",
   "Facundo Medina",
   "Gerónimo Rulli",
   "Giovani Lo Celso",
   "Giuliano Simeone",
   "Gonzalo Montiel",
   "José Manuel López",
   "Juan Musso",
   "Julián Álvarez",
   "Lautaro Martínez",
   "Leandro Paredes",
   "Lionel Messi",
   "Lisandro Martínez",
   "Marcos Senesi",
   "Nahuel Molina",
   "Nico González",
   "Nico Paz",
   "Nicolás Otamendi",
   "Nicolás Tagliafico",
   "Rodrigo De Paul",
   "Thiago Almada",
   "Valentín Barco"
  ],
  "be": [
   "Alexis Saelemaekers",
   "Amadou Onana",
   "Arthur Theate",
   "Axel Witsel",
   "Brandon Mechele",
   "Charles De Ketelaere",
   "Diego Moreira",
   "Dodi Lukébakio",
   "Hans Vanaken",
   "Joaquin Seys",
   "Jérémy Doku",
   "Kevin De Bruyne",
   "Koni De Winter",
   "Leandro Trossard",
   "Matias Fernandez-Pardo",
   "Maxim De Cuyper",
   "Mike Penders",
   "Nathan Ngoy",
   "Nicolas Raskin",
   "Romelu Lukaku",
   "Senne Lammens",
   "Thibaut Courtois",
   "Thomas Meunier",
   "Timothy Castagne",
   "Youri Tielemans"
  ],
  "no": [
   "Alexander Sørloth",
   "Andreas Schjelderup",
   "Antonio Nusa",
   "David Møller Wolfe",
   "Egil Selvik",
   "Erling Haaland",
   "Fredrik André Bjørkan",
   "Fredrik Aursnes",
   "Henrik Falchener",
   "Jens Petter Hauge",
   "Julian Ryerson",
   "Jørgen Strand Larsen",
   "Kristian Thorstvedt",
   "Kristoffer Ajer",
   "Leo Østigård",
   "Marcus Holmgren Pedersen",
   "Martin Ødegaard",
   "Morten Thorsby",
   "Oscar Bobb",
   "Patrick Berg",
   "Sander Berge",
   "Sander Tangvik",
   "Sondre Langas",
   "Thelo Aasgaard",
   "Torbjørn Heggem",
   "Ørjan Nyland"
  ],
  "se": [
   "Alexander Bernhardsson",
   "Alexander Isak",
   "Anthony Elanga",
   "Benjamin Nygren",
   "Besfort Zeneli",
   "Carl Starfelt",
   "Daniel Svensson",
   "Elliot Stroud",
   "Eric Smith",
   "Gabriel Gudmundsson",
   "Gustaf Lagerbielke",
   "Gustaf Nilsson",
   "Herman Johansson",
   "Hjalmar Ekdal",
   "Isak Hien",
   "Jacob Widell Zetterström",
   "Jesper Karlström",
   "Ken Sema",
   "Kristoffer Nordfeldt",
   "Lucas Bergvall",
   "Mattias Svanberg",
   "Taha Ali",
   "Victor Lindelöf",
   "Viktor Gyökeres",
   "Viktor Johansson",
   "Yasin Ayari"
  ],
  "hr": [
   "Andrej Kramarić",
   "Ante Budimir",
   "Dominik Kotarski",
   "Dominik Livaković",
   "Duje Caleta-Car",
   "Igor Matanovic",
   "Ivan Perišić",
   "Ivor Pandur",
   "Josip Stanišić",
   "Josip Šutalo",
   "Josko Gvardiol",
   "Kristijan Jakic",
   "Luka Modrić",
   "Luka Sucic",
   "Luka Vuskovic",
   "Marco Pasalic",
   "Marin Pongračić",
   "Mario Pasalic",
   "Martin Baturina",
   "Martin Erlic",
   "Mateo Kovačić",
   "Nikola Moro",
   "Nikola Vlasic",
   "Petar Musa",
   "Petar Sučić",
   "Toni Fruk"
  ],
  "de": [
   "Aleksandar Pavlović",
   "Alexander Nübel",
   "Angelo Stiller",
   "Antonio Rüdiger",
   "Assan Ouédraogo",
   "David Raum",
   "Deniz Undav",
   "Felix Nmecha",
   "Florian Wirtz",
   "Jamal Musiala",
   "Jamie Leweling",
   "Jonathan Tah",
   "Joshua Kimmich",
   "Kai Havertz",
   "Leon Goretzka",
   "Leroy Sané",
   "Malick Thiaw",
   "Manuel Neuer",
   "Maximilian Beier",
   "Nadiem Amiri",
   "Nathaniel Brown",
   "Nick Woltemade",
   "Nico Schlotterbeck",
   "Oliver Baumann",
   "Pascal Gross",
   "Waldemar Anton"
  ],
  "eg": [
   "Ahmed Fatouh",
   "Emam Ashour",
   "Haissem Hassan",
   "Hamdy Fathy",
   "Hamza Abdelkarim",
   "Hossam Abdelmaguid",
   "Ibrahim Adel",
   "Karim Hafez",
   "Mahdy Soliman",
   "Mahmoud Saber",
   "Marawan Attia",
   "Mohamed Abdelmoneim",
   "Mohamed Alaa",
   "Mohamed El Shenawy",
   "Mohamed Hany",
   "Mohamed Salah",
   "Mohanad Lashin",
   "Mostafa Shoubir",
   "Mostafa Zico",
   "Nabil Donga",
   "Omar Marmoush",
   "Ramy Rabia",
   "Tarek Alaa",
   "Trezeguet",
   "Yasser Ibrahim",
   "Zizo"
  ],
  "ec": [
   "Alan Franco",
   "Alan Minda",
   "Angelo Preciado",
   "Anthony Valencia",
   "Denil Castillo",
   "Enner Valencia",
   "Félix Torres",
   "Gonzalo Plata",
   "Gonzalo Valle",
   "Hernán Galíndez",
   "Jackson Porozo",
   "Jeremy Arévalo",
   "Joel Ordóñez",
   "John Yeboah",
   "Jordy Alcívar",
   "Jordy Caicedo",
   "Kendry Páez",
   "Kevin Rodríguez",
   "Moisés Caicedo",
   "Moisés Ramírez",
   "Nilson Angulo",
   "Pedro Vite",
   "Pervis Estupiñán",
   "Piero Hincapié",
   "Willian Pacho",
   "Yaimar Medina"
  ],
  "ci": [
   "Alban Lafont",
   "Amad Diallo",
   "Ange-Yoan Bonny",
   "Bazoumana Touré",
   "Christ Inao Oulaï",
   "Christopher Operi",
   "Elye Wahi",
   "Emmanuel Agbadou",
   "Evan Ndicka",
   "Evann Guessand",
   "Franck Kessié",
   "Ghislain Konan",
   "Guela Doué",
   "Ibrahim Sangaré",
   "Jean Michaël Seri",
   "Mohamed Koné",
   "Nicolas Pépé",
   "Odilon Kossounou",
   "Oumar Diakité",
   "Ousmane Diomandé",
   "Parfait Guiagon",
   "Seko Fofana",
   "Simon Adingra",
   "Wilfried Singo",
   "Yahia Fofana",
   "Yan Diomande"
  ],
  "uy": [
   "Agustín Canobbio",
   "Brian Rodríguez",
   "Darwin Núñez",
   "Emiliano Martínez",
   "Facundo Pellistri",
   "Federico Valverde",
   "Federico Viñas",
   "Fernando Muslera",
   "Giorgian de Arrascaeta",
   "Guillermo Varela",
   "Joaquín Piquerez",
   "José María Giménez",
   "Juan Manuel Sanabria",
   "Manuel Ugarte",
   "Mathías Olivera",
   "Matías Viña",
   "Maximiliano Araújo",
   "Nicolás de la Cruz",
   "Rodrigo Aguirre",
   "Rodrigo Bentancur",
   "Rodrigo Zalazar",
   "Ronald Araújo",
   "Santiago Bueno",
   "Santiago Mele",
   "Sebastián Cáceres",
   "Sergio Rochet"
  ],
  "gh": [
   "Abdul Mumin",
   "Alidu Seidu",
   "Antoine Semenyo",
   "Augustine Boakye",
   "Baba Rahman",
   "Benjamin Asare",
   "Brandon Thomas-Asante",
   "Caleb Yirenkyi",
   "Christopher Bonsu Baah",
   "Derrick Luckassen",
   "Elisha Owusu",
   "Ernest Nuamah",
   "Fatawu Issahaku",
   "Gideon Mensah",
   "Iñaki Williams",
   "Jerome Opoku",
   "Jonas Adjetey",
   "Jordan Ayew",
   "Joseph Anang",
   "Kamaldeen Sulemana",
   "Kojo Peprah Oppong",
   "Kwasi Sibo",
   "Lawrence Ati Zigi",
   "Marvin Senaya",
   "Prince Adu",
   "Thomas Partey"
  ],
  "at": [
   "Alessandro Schöpf",
   "Alexander Prass",
   "Alexander Schlager",
   "Carney Chukwuemeka",
   "David Affengruber",
   "David Alaba",
   "Dejan Ljubicic",
   "Florian Grillitsch",
   "Florian Wiegele",
   "Kevin Danso",
   "Konrad Laimer",
   "Marcel Sabitzer",
   "Marco Friedl",
   "Marko Arnautović",
   "Michael Gregoritsch",
   "Michael Svoboda",
   "Nicolas Seiwald",
   "Patrick Pentz",
   "Patrick Wimmer",
   "Paul Wanner",
   "Philipp Lienhart",
   "Phillipp Mwene",
   "Romano Schmid",
   "Sasa Kalajdzic",
   "Stefan Posch",
   "Xaver Schlager"
  ],
  "co": [
   "Andrés Gómez",
   "Camilo Vargas",
   "Cucho Hernández",
   "Daniel Muñoz",
   "David Ospina",
   "Davinson Sánchez",
   "Deiver Machado",
   "Gustavo Puerta",
   "James Rodríguez",
   "Jefferson Lerma",
   "Jhon Arias",
   "Jhon Córdoba",
   "Jhon Lucumí",
   "Johan Mojica",
   "Jorge Carrascal",
   "Juan Fernando Quintero",
   "Juan Portilla",
   "Jáminton Campaz",
   "Kevin Castaño",
   "Luis Díaz",
   "Luis Suárez",
   "Richard Ríos",
   "Santiago Arias",
   "Willer Ditta",
   "Yerry Mina",
   "Álvaro Montero"
  ],
  "us": [
   "Alejandro Zendejas",
   "Alex Freeman",
   "Antonee Robinson",
   "Auston Trusty",
   "Brenden Aaronson",
   "Chris Brady",
   "Chris Richards",
   "Christian Pulisic",
   "Cristian Roldan",
   "Folarin Balogun",
   "Giovanni Reyna",
   "Haji Wright",
   "Joe Scally",
   "Malik Tillman",
   "Mark McKenzie",
   "Matt Freese",
   "Matt Turner",
   "Max Arfsten",
   "Miles Robinson",
   "Ricardo Pepi",
   "Sebastian Berhalter",
   "Sergiño Dest",
   "Tim Ream",
   "Timothy Weah",
   "Tyler Adams",
   "Weston McKennie"
  ],
  "ch": [
   "Ardon Jashari",
   "Aurèle Amenda",
   "Breel Embolo",
   "Cedric Itten",
   "Christian Fassnacht",
   "Dan Ndoye",
   "Denis Zakaria",
   "Djibril Sow",
   "Eray Cömert",
   "Fabian Rieder",
   "Granit Xhaka",
   "Gregor Kobel",
   "Johan Manzambi",
   "Luca Jaquez",
   "Manuel Akanji",
   "Marvin Keller",
   "Michel Aebischer",
   "Miro Muheim",
   "Nico Elvedi",
   "Noah Okafor",
   "Remo Freuler",
   "Ricardo Rodríguez",
   "Ruben Vargas",
   "Silvan Widmer",
   "Yvon Mvogo",
   "Zeki Amdouni"
  ],
  "tr": [
   "Abdülkerim Bardakcı",
   "Altay Bayindir",
   "Arda Güler",
   "Barış Alper Yılmaz",
   "Can Uzun",
   "Deniz Gül",
   "Eren Elmali",
   "Ferdi Kadıoğlu",
   "Hakan Çalhanoğlu",
   "Irfan Can Kahveci",
   "Ismail Yüksek",
   "Kaan Ayhan",
   "Kenan Yıldız",
   "Kerem Aktürkoğlu",
   "Merih Demiral",
   "Mert Günok",
   "Mert Müldür",
   "Oguz Aydin",
   "Orkun Kökçü",
   "Ozan Kabak",
   "Salih Özcan",
   "Samet Akaydin",
   "Uğurcan Çakır",
   "Yunus Akgün",
   "Zeki Çelik",
   "Çaglar Söyüncü"
  ],
  "ma": [
   "Achraf Hakimi",
   "Ahmed Reda Tagnaouti",
   "Amine Sbaï",
   "Anass Salah-Eddine",
   "Ayoub El Kaabi",
   "Ayoube Amaimouni",
   "Ayyoub Bouaddi",
   "Azzedine Ounahi",
   "Bilal El Khannouss",
   "Brahim Díaz",
   "Chadi Riad",
   "Chemsdine Talbi",
   "Gessime Yassine",
   "Ismael Saibari",
   "Issa Diop",
   "Marwane Saadane",
   "Munir El Kajoui",
   "Neil El Aynaoui",
   "Noussair Mazraoui",
   "Redouane Halhal",
   "Samir El Mourabet",
   "Sofyan Amrabat",
   "Soufiane Rahimi",
   "Yassine Bounou",
   "Youssef Belammari",
   "Zakaria El Ouahdi"
  ],
  "gb-sct": [
   "Aaron Hickey",
   "Andy Robertson",
   "Angus Gunn",
   "Anthony Ralston",
   "Ben Gannon-Doak",
   "Che Adams",
   "Craig Gordon",
   "Dominic Hyam",
   "Findlay Curtis",
   "George Hirst",
   "Grant Hanley",
   "Jack Hendry",
   "John McGinn",
   "John Souttar",
   "Kenny McLean",
   "Kieran Tierney",
   "Lawrence Shankland",
   "Lewis Ferguson",
   "Liam Kelly",
   "Lyndon Dykes",
   "Nathan Patterson",
   "Ross Stewart",
   "Ryan Christie",
   "Scott McKenna",
   "Scott McTominay",
   "Tyler Fletcher"
  ],
  "sn": [
   "Abdoulaye Seck",
   "Antoine Mendy",
   "Assane Diao",
   "Bamba Dieng",
   "Bara Sapoko Ndiaye",
   "Cherif Ndiaye",
   "El Hadji Malick Diouf",
   "Habib Diarra",
   "Ibrahim Mbaye",
   "Idrissa Gueye",
   "Iliman Ndiaye",
   "Ismail Jakobs",
   "Ismaïla Sarr",
   "Kalidou Koulibaly",
   "Krépin Diatta",
   "Lamine Camara",
   "Mamadou Sarr",
   "Mory Diaw",
   "Moussa Niakhaté",
   "Nicolas Jackson",
   "Pape Gueye",
   "Pape Matar Sarr",
   "Pathé Ciss",
   "Sadio Mané",
   "Yehvann Diouf",
   "Édouard Mendy"
  ],
  "mx": [
   "Alexis Vega",
   "Armando González",
   "Brian Gutiérrez",
   "Carlos Acevedo",
   "César Huerta",
   "César Montes",
   "Edson Álvarez",
   "Gilberto Mora",
   "Guillermo Martínez",
   "Guillermo Ochoa",
   "Israel Reyes",
   "Jesús Gallardo",
   "Johan Vásquez",
   "Jorge Sánchez",
   "Julián Quiñones",
   "Luis Chávez",
   "Luis Romo",
   "Mateo Chávez",
   "Obed Vargas",
   "Orbelín Pineda",
   "Raúl Jiménez",
   "Raúl Rangel",
   "Roberto Alvarado",
   "Santiago Gimenez",
   "Álvaro Fidalgo",
   "Érik Lira"
  ]
 }
};
