// Generated by scripts/fetch-wc.mjs — do not edit by hand.
window.WC = {
 "updated": "20260704",
 "players": {
  "Malik Tillman": {
   "g": 1,
   "a": 1,
   "yc": 0,
   "rc": 0
  },
  "Tyler Adams": {
   "g": 0,
   "a": 0,
   "yc": 1,
   "rc": 0
  },
  "Folarin Balogun": {
   "g": 3,
   "a": 0,
   "yc": 1,
   "rc": 1
  },
  "Christian Pulisic": {
   "g": 0,
   "a": 1,
   "yc": 0,
   "rc": 0
  },
  "Breel Embolo": {
   "g": 2,
   "a": 2,
   "yc": 0,
   "rc": 0
  },
  "Bruno Guimarães": {
   "g": 0,
   "a": 4,
   "yc": 0,
   "rc": 0
  },
  "Casemiro": {
   "g": 1,
   "a": 0,
   "yc": 2,
   "rc": 0
  },
  "Vinícius Júnior": {
   "g": 4,
   "a": 1,
   "yc": 0,
   "rc": 0
  },
  "Brahim Díaz": {
   "g": 0,
   "a": 2,
   "yc": 0,
   "rc": 0
  },
  "Nico Schlotterbeck": {
   "g": 1,
   "a": 0,
   "yc": 0,
   "rc": 0
  },
  "Joshua Kimmich": {
   "g": 0,
   "a": 2,
   "yc": 0,
   "rc": 0
  },
  "Florian Wirtz": {
   "g": 0,
   "a": 3,
   "yc": 0,
   "rc": 0
  },
  "Virgil van Dijk": {
   "g": 1,
   "a": 1,
   "yc": 0,
   "rc": 0
  },
  "Micky van de Ven": {
   "g": 0,
   "a": 0,
   "yc": 1,
   "rc": 0
  },
  "Ryan Gravenberch": {
   "g": 0,
   "a": 2,
   "yc": 0,
   "rc": 0
  },
  "Memphis Depay": {
   "g": 0,
   "a": 1,
   "yc": 1,
   "rc": 0
  },
  "Wilfried Singo": {
   "g": 0,
   "a": 1,
   "yc": 0,
   "rc": 0
  },
  "Seko Fofana": {
   "g": 0,
   "a": 0,
   "yc": 1,
   "rc": 0
  },
  "Franck Kessié": {
   "g": 1,
   "a": 0,
   "yc": 1,
   "rc": 0
  },
  "Amad Diallo": {
   "g": 2,
   "a": 0,
   "yc": 0,
   "rc": 0
  },
  "Lucas Bergvall": {
   "g": 0,
   "a": 1,
   "yc": 1,
   "rc": 0
  },
  "Yasin Ayari": {
   "g": 2,
   "a": 0,
   "yc": 1,
   "rc": 0
  },
  "Alexander Isak": {
   "g": 1,
   "a": 3,
   "yc": 0,
   "rc": 0
  },
  "Viktor Gyökeres": {
   "g": 1,
   "a": 2,
   "yc": 1,
   "rc": 0
  },
  "Pedri": {
   "g": 0,
   "a": 0,
   "yc": 1,
   "rc": 0
  },
  "Timothy Castagne": {
   "g": 0,
   "a": 0,
   "yc": 1,
   "rc": 0
  },
  "Ahmed Fatouh": {
   "g": 0,
   "a": 0,
   "yc": 1,
   "rc": 0
  },
  "Mohamed Salah": {
   "g": 1,
   "a": 2,
   "yc": 0,
   "rc": 0
  },
  "Adrien Rabiot": {
   "g": 0,
   "a": 1,
   "yc": 0,
   "rc": 0
  },
  "Kylian Mbappé": {
   "g": 6,
   "a": 2,
   "yc": 0,
   "rc": 0
  },
  "Michael Olise": {
   "g": 0,
   "a": 5,
   "yc": 0,
   "rc": 0
  },
  "David Møller Wolfe": {
   "g": 0,
   "a": 1,
   "yc": 0,
   "rc": 0
  },
  "Martin Ødegaard": {
   "g": 0,
   "a": 3,
   "yc": 0,
   "rc": 0
  },
  "Erling Haaland": {
   "g": 5,
   "a": 0,
   "yc": 0,
   "rc": 0
  },
  "Leo Østigård": {
   "g": 1,
   "a": 0,
   "yc": 0,
   "rc": 0
  },
  "Rodrigo De Paul": {
   "g": 0,
   "a": 1,
   "yc": 0,
   "rc": 0
  },
  "Lionel Messi": {
   "g": 7,
   "a": 0,
   "yc": 0,
   "rc": 0
  },
  "Xaver Schlager": {
   "g": 0,
   "a": 1,
   "yc": 0,
   "rc": 0
  },
  "Marcel Sabitzer": {
   "g": 1,
   "a": 0,
   "yc": 1,
   "rc": 0
  },
  "Marko Arnautović": {
   "g": 2,
   "a": 0,
   "yc": 1,
   "rc": 0
  },
  "João Neves": {
   "g": 1,
   "a": 0,
   "yc": 0,
   "rc": 0
  },
  "Pedro Neto": {
   "g": 0,
   "a": 1,
   "yc": 0,
   "rc": 0
  },
  "Bernardo Silva": {
   "g": 0,
   "a": 0,
   "yc": 1,
   "rc": 0
  },
  "Jude Bellingham": {
   "g": 2,
   "a": 1,
   "yc": 1,
   "rc": 0
  },
  "Declan Rice": {
   "g": 0,
   "a": 1,
   "yc": 1,
   "rc": 0
  },
  "Elliot Anderson": {
   "g": 0,
   "a": 1,
   "yc": 0,
   "rc": 0
  },
  "Harry Kane": {
   "g": 5,
   "a": 0,
   "yc": 0,
   "rc": 0
  },
  "Bukayo Saka": {
   "g": 0,
   "a": 2,
   "yc": 0,
   "rc": 0
  },
  "Ivan Perišić": {
   "g": 1,
   "a": 1,
   "yc": 2,
   "rc": 0
  },
  "Petar Sučić": {
   "g": 1,
   "a": 1,
   "yc": 1,
   "rc": 0
  },
  "Johan Mojica": {
   "g": 0,
   "a": 0,
   "yc": 1,
   "rc": 0
  },
  "Daniel Muñoz": {
   "g": 2,
   "a": 0,
   "yc": 0,
   "rc": 0
  },
  "Luis Díaz": {
   "g": 1,
   "a": 1,
   "yc": 0,
   "rc": 0
  },
  "Ruben Vargas": {
   "g": 2,
   "a": 1,
   "yc": 0,
   "rc": 0
  },
  "Nico Elvedi": {
   "g": 0,
   "a": 0,
   "yc": 1,
   "rc": 0
  },
  "Granit Xhaka": {
   "g": 1,
   "a": 0,
   "yc": 1,
   "rc": 0
  },
  "Chris Richards": {
   "g": 0,
   "a": 0,
   "yc": 1,
   "rc": 0
  },
  "Antonee Robinson": {
   "g": 0,
   "a": 0,
   "yc": 1,
   "rc": 0
  },
  "Matheus Cunha": {
   "g": 3,
   "a": 0,
   "yc": 0,
   "rc": 0
  },
  "Denzel Dumfries": {
   "g": 0,
   "a": 2,
   "yc": 0,
   "rc": 0
  },
  "Cody Gakpo": {
   "g": 3,
   "a": 1,
   "yc": 0,
   "rc": 0
  },
  "Anthony Elanga": {
   "g": 2,
   "a": 0,
   "yc": 0,
   "rc": 0
  },
  "Gabriel Gudmundsson": {
   "g": 0,
   "a": 0,
   "yc": 1,
   "rc": 0
  },
  "Dani Olmo": {
   "g": 0,
   "a": 1,
   "yc": 0,
   "rc": 0
  },
  "Mikel Oyarzabal": {
   "g": 4,
   "a": 1,
   "yc": 0,
   "rc": 0
  },
  "Lamine Yamal": {
   "g": 1,
   "a": 0,
   "yc": 0,
   "rc": 0
  },
  "Rodrigo Bentancur": {
   "g": 0,
   "a": 0,
   "yc": 1,
   "rc": 0
  },
  "Mohamed Hany": {
   "g": 0,
   "a": 1,
   "yc": 0,
   "rc": 0
  },
  "Trezeguet": {
   "g": 1,
   "a": 1,
   "yc": 0,
   "rc": 0
  },
  "Konrad Laimer": {
   "g": 0,
   "a": 1,
   "yc": 1,
   "rc": 0
  },
  "Stefan Posch": {
   "g": 0,
   "a": 0,
   "yc": 2,
   "rc": 0
  },
  "Ousmane Dembélé": {
   "g": 4,
   "a": 2,
   "yc": 0,
   "rc": 0
  },
  "Nuno Mendes": {
   "g": 1,
   "a": 0,
   "yc": 0,
   "rc": 0
  },
  "João Cancelo": {
   "g": 0,
   "a": 1,
   "yc": 0,
   "rc": 0
  },
  "Bruno Fernandes": {
   "g": 0,
   "a": 1,
   "yc": 0,
   "rc": 0
  },
  "Cristiano Ronaldo": {
   "g": 3,
   "a": 0,
   "yc": 0,
   "rc": 0
  },
  "Rafael Leão": {
   "g": 1,
   "a": 1,
   "yc": 0,
   "rc": 0
  },
  "Iñaki Williams": {
   "g": 0,
   "a": 0,
   "yc": 1,
   "rc": 0
  },
  "Josip Stanišić": {
   "g": 0,
   "a": 1,
   "yc": 0,
   "rc": 0
  },
  "Ante Budimir": {
   "g": 1,
   "a": 0,
   "yc": 0,
   "rc": 0
  },
  "Jhon Lucumí": {
   "g": 0,
   "a": 0,
   "yc": 1,
   "rc": 0
  },
  "Jefferson Lerma": {
   "g": 0,
   "a": 0,
   "yc": 1,
   "rc": 0
  },
  "Achraf Hakimi": {
   "g": 1,
   "a": 1,
   "yc": 0,
   "rc": 0
  },
  "Ibrahim Sangaré": {
   "g": 0,
   "a": 1,
   "yc": 0,
   "rc": 0
  },
  "Piero Hincapié": {
   "g": 0,
   "a": 0,
   "yc": 1,
   "rc": 1
  },
  "Pedro Vite": {
   "g": 0,
   "a": 1,
   "yc": 0,
   "rc": 0
  },
  "Nilson Angulo": {
   "g": 1,
   "a": 0,
   "yc": 0,
   "rc": 0
  },
  "Gonzalo Plata": {
   "g": 1,
   "a": 0,
   "yc": 1,
   "rc": 0
  },
  "Aleksandar Pavlović": {
   "g": 0,
   "a": 0,
   "yc": 1,
   "rc": 0
  },
  "Leroy Sané": {
   "g": 1,
   "a": 0,
   "yc": 0,
   "rc": 0
  },
  "Isak Hien": {
   "g": 0,
   "a": 0,
   "yc": 1,
   "rc": 0
  },
  "Tijjani Reijnders": {
   "g": 0,
   "a": 1,
   "yc": 0,
   "rc": 0
  },
  "Orkun Kökçü": {
   "g": 0,
   "a": 1,
   "yc": 0,
   "rc": 0
  },
  "Barış Alper Yılmaz": {
   "g": 1,
   "a": 1,
   "yc": 0,
   "rc": 0
  },
  "Arda Güler": {
   "g": 1,
   "a": 0,
   "yc": 0,
   "rc": 0
  },
  "Thelo Aasgaard": {
   "g": 1,
   "a": 0,
   "yc": 0,
   "rc": 0
  },
  "Aurélien Tchouaméni": {
   "g": 0,
   "a": 1,
   "yc": 1,
   "rc": 0
  },
  "Désiré Doué": {
   "g": 1,
   "a": 0,
   "yc": 0,
   "rc": 0
  },
  "Álex Baena": {
   "g": 1,
   "a": 1,
   "yc": 1,
   "rc": 0
  },
  "Kevin De Bruyne": {
   "g": 1,
   "a": 0,
   "yc": 0,
   "rc": 0
  },
  "Alexis Saelemaekers": {
   "g": 1,
   "a": 0,
   "yc": 0,
   "rc": 0
  },
  "Mateo Kovačić": {
   "g": 0,
   "a": 1,
   "yc": 0,
   "rc": 0
  },
  "Luka Modrić": {
   "g": 0,
   "a": 1,
   "yc": 1,
   "rc": 0
  },
  "Lautaro Martínez": {
   "g": 1,
   "a": 0,
   "yc": 0,
   "rc": 0
  },
  "Gabriel Magalhães": {
   "g": 0,
   "a": 1,
   "yc": 0,
   "rc": 0
  },
  "Antonio Nusa": {
   "g": 1,
   "a": 0,
   "yc": 1,
   "rc": 0
  },
  "Moisés Caicedo": {
   "g": 0,
   "a": 0,
   "yc": 1,
   "rc": 0
  },
  "Kendry Páez": {
   "g": 0,
   "a": 0,
   "yc": 1,
   "rc": 0
  },
  "Anthony Gordon": {
   "g": 0,
   "a": 2,
   "yc": 0,
   "rc": 0
  },
  "Youri Tielemans": {
   "g": 2,
   "a": 0,
   "yc": 0,
   "rc": 0
  },
  "Marc Cucurella": {
   "g": 0,
   "a": 2,
   "yc": 0,
   "rc": 0
  },
  "Pedro Porro": {
   "g": 1,
   "a": 0,
   "yc": 0,
   "rc": 0
  },
  "Rúben Dias": {
   "g": 0,
   "a": 0,
   "yc": 1,
   "rc": 0
  },
  "Dan Ndoye": {
   "g": 1,
   "a": 0,
   "yc": 0,
   "rc": 0
  },
  "Alexis Mac Allister": {
   "g": 0,
   "a": 1,
   "yc": 0,
   "rc": 0
  },
  "Jhon Arias": {
   "g": 1,
   "a": 0,
   "yc": 1,
   "rc": 0
  },
  "Richard Ríos": {
   "g": 0,
   "a": 0,
   "yc": 1,
   "rc": 0
  }
 },
 "nations": {
  "gb-eng": "active",
  "fr": "active",
  "br": "active",
  "es": "active",
  "nl": "out",
  "pt": "active",
  "ar": "active",
  "be": "active",
  "it": "nq",
  "no": "active",
  "se": "out",
  "hr": "out",
  "hu": "nq",
  "gb-nir": "nq",
  "de": "out",
  "eg": "active",
  "ec": "out",
  "ci": "nq",
  "dk": "nq",
  "cm": "nq",
  "si": "nq",
  "uy": "out",
  "gh": "out",
  "pl": "nq",
  "at": "out",
  "co": "active",
  "rs": "nq",
  "us": "active",
  "ch": "active",
  "tr": "out",
  "ma": "active",
  "ge": "nq"
 }
};
