// Generates seasons.js: final 2025-26 domestic league standings for the 13 clubs, from ESPN.
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";

const root = path.dirname(path.dirname(fileURLToPath(import.meta.url)));

const LEAGUES = {
  "eng.1": {
    label: "Premier League",
    teams: {
      Arsenal: "Arsenal",
      "Manchester City": "Manchester City",
      Liverpool: "Liverpool",
      Chelsea: "Chelsea",
      "Manchester United": "Manchester United",
      "Tottenham Hotspur": "Tottenham Hotspur",
    },
  },
  "esp.1": {
    label: "LaLiga",
    teams: { "Real Madrid": "Real Madrid", Barcelona: "Barcelona", "Atlético Madrid": "Atlético Madrid" },
  },
  "ger.1": { label: "Bundesliga", teams: { "Bayern Munich": "Bayern Munich" } },
  "ita.1": { label: "Serie A", teams: { "Inter Milan": "Internazionale", "AC Milan": "AC Milan" } },
  "fra.1": { label: "Ligue 1", teams: { "Paris Saint-Germain": "Paris Saint-Germain" } },
};

const out = {};
for (const [league, cfg] of Object.entries(LEAGUES)) {
  const res = await fetch(`https://site.api.espn.com/apis/v2/sports/soccer/${league}/standings?season=2025`, {
    headers: { "User-Agent": "Mozilla/5.0" },
  });
  if (!res.ok) {
    console.log(`${league}: HTTP ${res.status}`);
    continue;
  }
  const data = await res.json();
  const entries = data.children?.[0]?.standings?.entries ?? data.standings?.entries ?? [];
  for (const [ourName, espnName] of Object.entries(cfg.teams)) {
    const entry = entries.find((e) => e.team?.displayName === espnName);
    if (!entry) {
      console.log(`  MISS: ${ourName} (${espnName}) in ${league}`);
      continue;
    }
    const s = Object.fromEntries(entry.stats.map((x) => [x.name, x.value ?? x.displayValue]));
    out[ourName] = {
      league: cfg.label,
      season: "2025-26",
      pos: s.rank,
      pts: s.points,
      w: s.wins,
      d: s.ties,
      l: s.losses,
      gd: s.pointDifferential,
    };
    console.log(`  ${ourName}: #${s.rank} ${s.points}pts W${s.wins} D${s.ties} L${s.losses} GD${s.pointDifferential}`);
  }
}

writeFileSync(
  path.join(root, "seasons.js"),
  `// Generated by scripts/fetch-seasons.mjs — do not edit by hand.\nwindow.CLUB_SEASONS = ${JSON.stringify(out, null, 1)};\n`
);
console.log(`Wrote seasons.js: ${Object.keys(out).length} clubs`);
