// Generates bios.js: { "Player Name": { d: description, born: "5 September 2001", b: short bio } }
// from each player's Wikipedia summary. Incremental — reruns only fetch what's missing.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";
import { WIKI_OVERRIDES } from "./wiki-overrides.mjs";

const root = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const APP_DATA = new Function(
  `const window={}; ${readFileSync(path.join(root, "data.js"), "utf8")}; return window.APP_DATA;`
)();

const UA = { "User-Agent": "lineups-app/1.0 (personal project)" };
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

const players = new Set();
for (const club of APP_DATA.clubs) for (const p of club.rows.flat()) players.add(p.name);
for (const nation of Object.values(APP_DATA.nations)) for (const p of nation.rows.flat()) players.add(p.name);

async function summary(title) {
  let res;
  for (let attempt = 0; attempt < 4; attempt++) {
    res = await fetch(
      `https://en.wikipedia.org/api/rest_v1/page/summary/${encodeURIComponent(title.replace(/ /g, "_"))}`,
      { headers: UA }
    );
    if (res.status !== 429 && res.status < 500) break;
    await sleep(1500 * (attempt + 1));
  }
  if (!res.ok) return null;
  const d = await res.json();
  if (d.type === "disambiguation") return null;
  if (!/foot|goalkeeper|soccer/.test(`${d.description ?? ""} ${d.extract ?? ""}`.toLowerCase())) return null;
  return d;
}

// first two sentences, capped at ~340 chars
function shorten(extract) {
  if (!extract) return "";
  const sentences = extract.replace(/\s+/g, " ").split(/(?<=[.!?])\s+(?=[A-ZÀ-Þ])/);
  let out = "";
  for (const s of sentences) {
    if (out && (out + " " + s).length > 340) break;
    out = out ? out + " " + s : s;
    if (out.length > 200) break;
  }
  return out;
}

let bios = {};
try {
  bios = new Function(
    `const window={}; ${readFileSync(path.join(root, "bios.js"), "utf8")}; return window.PLAYER_BIOS;`
  )() ?? {};
  console.log(`Resuming with ${Object.keys(bios).length} cached bios`);
} catch {}

const misses = [];
for (const name of players) {
  if (bios[name]) continue;
  let data = null;
  for (const t of [...(WIKI_OVERRIDES[name] ?? []), name, `${name} (footballer)`]) {
    data = await summary(t);
    if (data) break;
    await sleep(250);
  }
  if (!data) {
    misses.push(name);
    continue;
  }
  const born =
    data.extract?.match(/born[^)]*?(\d{1,2} \w+ \d{4})/)?.[1] ??
    data.description?.match(/born (\d{4})/)?.[1] ??
    null;
  bios[name] = { d: data.description ?? "", born, b: shorten(data.extract) };
  await sleep(300);
}

writeFileSync(
  path.join(root, "bios.js"),
  `// Generated by scripts/fetch-bios.mjs — do not edit by hand.\nwindow.PLAYER_BIOS = ${JSON.stringify(bios, null, 1)};\n`
);
console.log(`Wrote bios.js: ${Object.keys(bios).length}/${players.size}`);
if (misses.length) console.log(`Missing:\n  ${misses.join("\n  ")}`);
